// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccessRequestCreate
 */
export type AccessRequestCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Organization
     */
    organization?: string | null;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * AccessRequestsProcessRequest
 */
export type AccessRequestsProcessRequest = {
    /**
     * Ids
     */
    ids: Array<string>;
    /**
     * Action
     */
    action: 'approve' | 'deny';
};

/**
 * AgentConfig
 */
export type AgentConfig = {
    /**
     * Model
     */
    model?: string;
    /**
     * Temperature
     */
    temperature?: number;
    lang?: LanguageCode;
    /**
     * Include
     */
    include?: boolean;
};

/**
 * AgentConfigs
 */
export type AgentConfigsInput = {
    probing?: ProbingAgentConfig;
    classification?: AgentConfig;
    history?: AgentConfig;
    security?: SecurityConfig;
    visual?: VisualConfig;
    answering?: AgentConfig;
};

/**
 * AgentConfigs
 */
export type AgentConfigsOutput = {
    probing?: ProbingAgentConfig;
    classification?: AgentConfig;
    history?: AgentConfig;
    security?: SecurityConfig;
    visual?: VisualConfig;
    answering?: AgentConfig;
};

/**
 * AnalysisCategoryCreate
 */
export type AnalysisCategoryCreate = {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    type: AnalysisType;
    /**
     * Min Value
     */
    min_value?: number | null;
    /**
     * Max Value
     */
    max_value?: number | null;
};

/**
 * AnalysisCategoryPublic
 */
export type AnalysisCategoryPublic = {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    type: AnalysisType;
    /**
     * Min Value
     */
    min_value?: number | null;
    /**
     * Max Value
     */
    max_value?: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AnalysisType
 */
export type AnalysisType = 'tag' | 'score';

/**
 * AnnotationValueCreate
 */
export type AnnotationValueCreate = {
    /**
     * Category Id
     */
    category_id: string;
    /**
     * Value Int
     */
    value_int: number;
};

/**
 * AnnotationValuePublic
 */
export type AnnotationValuePublic = {
    /**
     * Category Id
     */
    category_id: string;
    /**
     * Value Int
     */
    value_int: number;
    /**
     * Id
     */
    id: string;
};

/**
 * AnswerLength
 */
export type AnswerLength = 'short' | 'medium' | 'long';

/**
 * BackgroundInfoOptions
 *
 * Dataclass representing the possible values for the background info of the synthetic agents
 */
export type BackgroundInfoOptionsInput = {
    /**
     * Names Gender
     */
    names_gender: Array<[
        string,
        string
    ]>;
    /**
     * Age Range
     */
    age_range?: [
        number,
        number
    ];
    /**
     * Educations
     */
    educations: Array<string>;
    /**
     * Occupations
     */
    occupations: Array<string>;
    /**
     * Locations
     */
    locations: Array<string>;
    /**
     * Personalities
     */
    personalities: Array<string>;
    communication_traits: CommunicationTraits;
    /**
     * Extra Traits
     */
    extra_traits?: Array<{
        [key: string]: string;
    }> | Array<string> | null;
    /**
     * Refusal Rate
     */
    refusal_rate?: [
        number,
        number
    ] | null;
};

/**
 * BackgroundInfoOptions
 *
 * Dataclass representing the possible values for the background info of the synthetic agents
 */
export type BackgroundInfoOptionsOutput = {
    /**
     * Names Gender
     */
    names_gender: Array<[
        string,
        string
    ]>;
    /**
     * Age Range
     */
    age_range?: [
        number,
        number
    ];
    /**
     * Educations
     */
    educations: Array<string>;
    /**
     * Occupations
     */
    occupations: Array<string>;
    /**
     * Locations
     */
    locations: Array<string>;
    /**
     * Personalities
     */
    personalities: Array<string>;
    communication_traits: CommunicationTraits;
    /**
     * Extra Traits
     */
    extra_traits?: Array<{
        [key: string]: string;
    }> | Array<string> | null;
    /**
     * Refusal Rate
     */
    refusal_rate?: [
        number,
        number
    ] | null;
};

/**
 * Body_create_welcome
 */
export type BodyCreateWelcome = {
    /**
     * Title
     */
    title: string;
    /**
     * Text
     */
    text: string;
    /**
     * Email
     */
    email: string;
    /**
     * Video
     */
    video?: Blob | File | null;
};

/**
 * Broadcast
 */
export type Broadcast = {
    /**
     * Message
     */
    message: string;
};

/**
 * CommunicationTrait
 */
export type CommunicationTrait = {
    length: AnswerLength;
    /**
     * Style
     */
    style: string;
    /**
     * Tone
     */
    tone: string;
};

/**
 * CommunicationTraits
 */
export type CommunicationTraits = {
    /**
     * Length
     */
    length: Array<AnswerLength | string>;
    /**
     * Style
     */
    style: Array<string>;
    /**
     * Tone
     */
    tone: Array<string>;
};

/**
 * Condition
 *
 * Create a condition that must be met to ask a question
 */
export type Condition = {
    type: ConditionType;
    trigger_type: ConditionTriggerType;
    question_context: QuestionContext;
    /**
     * Trigger Value
     */
    trigger_value: unknown;
    action: ConditionAction;
};

/**
 * ConditionAction
 */
export type ConditionAction = 'skip_section' | 'skip_question' | 'end_interview';

/**
 * ConditionTriggerType
 */
export type ConditionTriggerType = 're' | 'classification';

/**
 * ConditionType
 */
export type ConditionType = 'yes/no';

/**
 * Consent
 */
export type Consent = {
    /**
     * Title
     */
    title: string;
    /**
     * Text
     */
    text: string;
};

/**
 * ContextType
 *
 * Context to be upsed for probing
 */
export type ContextType = 'section' | 'question';

/**
 * CreateProjectRequest
 */
export type CreateProjectRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Folder Id
     */
    folder_id: string;
    default_language: LanguageCode;
};

/**
 * DeleteInterviewRequest
 */
export type DeleteInterviewRequest = {
    /**
     * Interview Ids
     */
    interview_ids: Array<string>;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * ExperimentCreate
 */
export type ExperimentCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Project Ids
     */
    project_ids: Array<string>;
    /**
     * Weights
     */
    weights?: Array<number> | null;
};

/**
 * ExportMessagesRequest
 */
export type ExportMessagesRequest = {
    /**
     * Interview Ids
     */
    interview_ids: Array<string>;
    /**
     * Format
     */
    format?: 'csv' | 'xlsx';
};

/**
 * Feedback
 */
export type Feedback = 'positive' | 'negative';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Image
 *
 * An image to show the interviewee
 */
export type Image = {
    /**
     * Primer
     *
     * A primer to show the interviewee before showing the image
     */
    primer?: string | null;
    /**
     * Description
     *
     * A description of the image used to guide the probing
     */
    description: string;
    /**
     * Alt
     *
     * The alt text for the image for accessibility
     */
    alt: string;
    /**
     * Name
     *
     * The filename
     */
    name: string;
    /**
     * Data
     */
    data?: string | null;
};

/**
 * InterviewConfig
 */
export type InterviewConfig = {
    default_language?: LanguageCode;
    /**
     * Referer Id Key
     *
     * Key for the value of the id sent in the referer header
     */
    referer_id_key?: string | null;
    /**
     * With Consent
     *
     * Whether to ask for consent before starting the interview
     */
    with_consent?: boolean;
    /**
     * With Welcome
     *
     * Whether to show a welcome message before starting the interview
     */
    with_welcome?: boolean;
};

/**
 * InterviewGuide
 */
export type InterviewGuideInput = {
    /**
     * Framing
     *
     * A description of the interview and its purpose. Only used by the model.
     */
    framing?: string | null;
    /**
     * Introduction
     *
     * An introduction to the interview. Displayed to the interviewee as the first message. They whon't be able to respond to this message.
     */
    introduction?: string | null;
    /**
     * Question Sections
     *
     * A list of sections containing questions to ask the interviewee
     */
    question_sections?: Array<QuestionSectionQuestionInput>;
    /**
     * Outro
     *
     * An outro to the interview. Displayed to the interviewee as the last message. They will not be able to answer this message.
     */
    outro?: string | null;
};

/**
 * InterviewGuide
 */
export type InterviewGuideOutput = {
    /**
     * Framing
     *
     * A description of the interview and its purpose. Only used by the model.
     */
    framing?: string | null;
    /**
     * Introduction
     *
     * An introduction to the interview. Displayed to the interviewee as the first message. They whon't be able to respond to this message.
     */
    introduction?: string | null;
    /**
     * Question Sections
     *
     * A list of sections containing questions to ask the interviewee
     */
    question_sections?: Array<QuestionSectionQuestionOutput>;
    /**
     * Outro
     *
     * An outro to the interview. Displayed to the interviewee as the last message. They will not be able to answer this message.
     */
    outro?: string | null;
};

/**
 * InterviewGuideGenerationPromptRequest
 */
export type InterviewGuideGenerationPromptRequest = {
    /**
     * Prompt
     */
    prompt: string;
};

/**
 * InterviewMessage
 */
export type InterviewMessage = {
    /**
     * Message
     */
    message: string;
};

/**
 * InterviewSubject
 *
 * Dataclass representing the interview subject
 */
export type InterviewSubject = {
    /**
     * Name
     */
    name: string;
    /**
     * Age
     */
    age: number;
    /**
     * Gender
     */
    gender: string;
    /**
     * Education
     */
    education: string;
    /**
     * Occupation
     */
    occupation: string;
    /**
     * Location
     */
    location: string;
    /**
     * Personality
     */
    personality: string;
    communication_trait: CommunicationTrait;
    /**
     * Extra Traits
     */
    extra_traits?: {
        [key: string]: string;
    } | string | null;
    /**
     * Refusal Rate
     */
    refusal_rate?: number;
};

/**
 * IntervieweeCreate
 */
export type IntervieweeCreate = {
    /**
     * Interview Id
     */
    interview_id: string;
    /**
     * Project Id
     */
    project_id: string;
    interview_subject: InterviewSubject;
};

/**
 * Interviewer
 */
export type Interviewer = 'human' | 'ai';

export type LanguageCode = string;

/**
 * LanguageDict
 */
export type LanguageDict = {
    /**
     * Name
     */
    name: string;
    code: LanguageCode;
};

/**
 * LoginData
 */
export type LoginData = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MessageAnnotationCreate
 */
export type MessageAnnotationCreate = {
    /**
     * Message Id
     */
    message_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Comment
     */
    comment?: string | null;
    /**
     * Values
     */
    values: Array<AnnotationValueCreate>;
};

/**
 * MessageAnnotationPublic
 */
export type MessageAnnotationPublic = {
    /**
     * Message Id
     */
    message_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Comment
     */
    comment?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Values
     */
    values: Array<AnnotationValuePublic>;
};

/**
 * MessageFeedback
 */
export type MessageFeedback = {
    /**
     * Interview Id
     */
    interview_id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Message Id
     */
    message_id: number;
    feedback: Feedback | null;
};

/**
 * MessagePublic
 */
export type MessagePublic = {
    /**
     * Message Id
     */
    message_id: number;
    /**
     * Content
     */
    content: string;
    role: MessageRole;
    /**
     * Interview Id
     */
    interview_id: string;
    /**
     * Project Id
     */
    project_id: string;
    message_type?: MessageType;
    /**
     * Section
     */
    section?: number | null;
    /**
     * Main Question
     */
    main_question?: number | null;
    /**
     * Sub Question
     */
    sub_question?: number | null;
    /**
     * Is Introduction
     */
    is_introduction?: boolean;
    /**
     * Outro
     */
    outro?: boolean;
    /**
     * Timed
     */
    timed?: boolean;
    /**
     * Can Answer
     */
    can_answer?: boolean;
    /**
     * Include In History
     */
    include_in_history?: boolean;
    /**
     * Attachment
     */
    attachment?: string | null;
    feedback?: Feedback | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Image
     */
    image?: Image | Array<Image> | null;
    survey_item?: SurveyItem | null;
    /**
     * Id
     */
    id: string;
    /**
     * Annotations
     */
    annotations?: Array<MessageAnnotationPublic>;
    /**
     * Is Test
     */
    is_test: boolean;
    /**
     * Is Synthetic
     */
    is_synthetic: boolean;
};

/**
 * MessageRole
 */
export type MessageRole = 'system' | 'assistant' | 'user';

/**
 * MessageType
 */
export type MessageType = 'text' | 'image' | 'custom_token' | 'survey_item';

/**
 * ProbingAgentConfig
 */
export type ProbingAgentConfig = {
    /**
     * Model
     */
    model?: string;
    /**
     * Temperature
     */
    temperature?: number;
    lang?: LanguageCode;
    /**
     * Include
     */
    include?: boolean;
    /**
     * Few Shot Examples
     */
    few_shot_examples?: Array<string> | null;
};

/**
 * ProjectFolderCreate
 */
export type ProjectFolderCreate = {
    /**
     * Title
     */
    title: string;
};

/**
 * ProjectFolderDelete
 */
export type ProjectFolderDelete = {
    /**
     * Id
     */
    id: string;
};

/**
 * ProjectFolderEdit
 */
export type ProjectFolderEdit = {
    /**
     * Title
     */
    title: string;
    /**
     * Id
     */
    id: string;
};

/**
 * ProjectFolderPublic
 */
export type ProjectFolderPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Id
     */
    id: string;
};

/**
 * ProjectFolderWithProjects
 */
export type ProjectFolderWithProjects = {
    /**
     * Title
     */
    title: string;
    /**
     * Id
     */
    id: string;
    /**
     * Projects
     */
    projects: Array<ProjectPublic>;
};

/**
 * ProjectPublic
 */
export type ProjectPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Last Updated
     */
    last_updated?: string | null;
    status?: ProjectStatus;
    config: InterviewConfig;
    /**
     * N Interviews
     */
    n_interviews?: number | null;
    /**
     * Available Languages
     */
    available_languages?: Array<LanguageDict> | null;
    /**
     * Tests
     */
    tests?: Array<TestSetupPublic> | null;
};

/**
 * ProjectStatus
 */
export type ProjectStatus = 'active' | 'inactive';

/**
 * ProjectStatusChangeRequest
 */
export type ProjectStatusChangeRequest = {
    status: ProjectStatus;
};

/**
 * ProjectTitleUpdateRequest
 */
export type ProjectTitleUpdateRequest = {
    /**
     * Title
     */
    title: string;
};

/**
 * PromptTemplates
 */
export type PromptTemplates = {
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Instruction Prompt
     */
    instruction_prompt: string;
};

/**
 * PromptsUpdateRequest
 */
export type PromptsUpdateRequest = {
    probing_agent: PromptTemplates;
};

/**
 * Question
 *
 * A question that can be asked to the interviewee
 */
export type QuestionInput = {
    /**
     * Description
     *
     * A description of the question, may be used to reformulate the question and improve the relevance of the probes.
     */
    description?: string | null;
    /**
     * Main Question
     *
     * The question to ask the interviewee
     */
    main_question: string;
    /**
     * Alternative Main Questions
     *
     * List of alternative formulations of the main question, will be chosen at random.
     */
    alternative_main_questions?: Array<string> | null;
    /**
     * Probes
     *
     * A list of possible follow-up questions to ask after the main question
     */
    probes?: Array<string> | null;
    /**
     * Max Probes N
     *
     * Max number of probes
     */
    max_probes_n?: number | null;
    /**
     * Max Probes Time
     *
     * Max time to spend on probing, in seconds
     */
    max_probes_time?: number | null;
    /**
     * Can Answer
     *
     * Should the user be able to answer the question? Disable this to make the question into a message
     */
    can_answer?: boolean;
    /**
     * Exclude From History
     *
     * Exclude from the interview history. This means that the model will not use this question or the response as a context when it asks further questions.
     */
    exclude_from_history?: boolean;
    /**
     * Check If Answered
     *
     * Check if the question has already been answered under a previous question
     */
    check_if_answered?: boolean;
    /**
     * Check If Exhausted
     *
     * During the probing, check if the question has been exhausted and the model should continue to the next question.
     */
    check_if_exhausted?: boolean;
    /**
     * Can Skip
     *
     * Should the user be able to skip the question?
     */
    can_skip?: boolean;
    /**
     * Shuffle
     *
     * Should the question be shuffled?
     */
    shuffle?: boolean;
    /**
     * Create Segue
     *
     * Create a segue from the previous question, to possibly improve the flow of the interview.
     */
    create_segue?: boolean;
    /**
     * Variables
     *
     * Variables that can be used in the question, ie. uuid. In case they are supplied, they will be filled in before the question is asked. The question should be formatted with Jinja2 style templating.
     */
    variables?: Array<string> | null;
    survey_item?: SurveyItem | null;
    /**
     * References
     */
    references?: Array<Reference> | null;
    image?: Image | null;
    /**
     * User Image
     *
     * Whether the user should be able to upload an image as a response
     */
    user_image?: boolean;
    condition?: Condition | null;
    probing_context?: ContextType | null;
};

/**
 * Question
 *
 * A question that can be asked to the interviewee
 */
export type QuestionOutput = {
    /**
     * Description
     *
     * A description of the question, may be used to reformulate the question and improve the relevance of the probes.
     */
    description?: string | null;
    /**
     * Main Question
     *
     * The question to ask the interviewee
     */
    main_question: string;
    /**
     * Alternative Main Questions
     *
     * List of alternative formulations of the main question, will be chosen at random.
     */
    alternative_main_questions?: Array<string> | null;
    /**
     * Probes
     *
     * A list of possible follow-up questions to ask after the main question
     */
    probes?: Array<string> | null;
    /**
     * Max Probes N
     *
     * Max number of probes
     */
    max_probes_n?: number | null;
    /**
     * Max Probes Time
     *
     * Max time to spend on probing, in seconds
     */
    max_probes_time?: number | null;
    /**
     * Can Answer
     *
     * Should the user be able to answer the question? Disable this to make the question into a message
     */
    can_answer?: boolean;
    /**
     * Exclude From History
     *
     * Exclude from the interview history. This means that the model will not use this question or the response as a context when it asks further questions.
     */
    exclude_from_history?: boolean;
    /**
     * Check If Answered
     *
     * Check if the question has already been answered under a previous question
     */
    check_if_answered?: boolean;
    /**
     * Check If Exhausted
     *
     * During the probing, check if the question has been exhausted and the model should continue to the next question.
     */
    check_if_exhausted?: boolean;
    /**
     * Can Skip
     *
     * Should the user be able to skip the question?
     */
    can_skip?: boolean;
    /**
     * Shuffle
     *
     * Should the question be shuffled?
     */
    shuffle?: boolean;
    /**
     * Create Segue
     *
     * Create a segue from the previous question, to possibly improve the flow of the interview.
     */
    create_segue?: boolean;
    /**
     * Variables
     *
     * Variables that can be used in the question, ie. uuid. In case they are supplied, they will be filled in before the question is asked. The question should be formatted with Jinja2 style templating.
     */
    variables?: Array<string> | null;
    survey_item?: SurveyItem | null;
    /**
     * References
     */
    references?: Array<Reference> | null;
    image?: Image | null;
    /**
     * User Image
     *
     * Whether the user should be able to upload an image as a response
     */
    user_image?: boolean;
    condition?: Condition | null;
    probing_context?: ContextType | null;
};

/**
 * QuestionContext
 *
 * The index of a question in a section
 * section [int]: The index of the section
 * question [int]: The index of the question
 */
export type QuestionContext = {
    /**
     * Section
     */
    section: number;
    /**
     * Question
     */
    question: number;
    /**
     * Part
     */
    part?: 'main' | 'probes' | 'all';
};

export type QuestionIndex = [
    number,
    number
];

/**
 * QuestionSection[Question]
 */
export type QuestionSectionQuestionInput = {
    /**
     * Description
     *
     * A description of the section, used as context for the prober to limit its scope.
     */
    description: string;
    /**
     * Questions
     */
    questions: Array<QuestionInput>;
    /**
     * Shuffle
     *
     * Should the section be included in shuffling?
     */
    shuffle?: boolean;
};

/**
 * QuestionSection[Question]
 */
export type QuestionSectionQuestionOutput = {
    /**
     * Description
     *
     * A description of the section, used as context for the prober to limit its scope.
     */
    description: string;
    /**
     * Questions
     */
    questions: Array<QuestionOutput>;
    /**
     * Shuffle
     *
     * Should the section be included in shuffling?
     */
    shuffle?: boolean;
};

/**
 * Reference
 *
 * Create a reference to a previous answer, useful when refering back to a
 * previous answer, eg. an answer to a survey item. If used, the main question
 * must contains an empty `{}` as a placeholder for the referred answer.
 */
export type Reference = {
    question_index: QuestionIndex;
};

/**
 * Scope
 */
export type Scope = 'admin' | 'user' | 'guest';

/**
 * SecurityConfig
 */
export type SecurityConfig = {
    /**
     * Model
     */
    model?: string;
    /**
     * Temperature
     */
    temperature?: number;
    lang?: LanguageCode;
    /**
     * Include
     */
    include?: boolean;
    /**
     * Sensitive Subjects
     */
    sensitive_subjects?: Array<unknown> | null;
};

/**
 * SurveyItem
 */
export type SurveyItem = {
    type: SurveyItemType;
    /**
     * Options
     */
    options: Array<string | SurveyOption>;
    /**
     * Required
     */
    required?: boolean;
};

/**
 * SurveyItemType
 */
export type SurveyItemType = 'radio' | 'checkbox' | 'slider' | 'number' | 'date';

/**
 * SurveyOption
 *
 * An option for a survey item.
 * label [str]: The label for the option, will be displayed in the ui.
 * value [Optional[str]]: The value for the option, can be used as a point of reference later in the interview.
 * tip: [Optional[str]]: A tip to show the interviewee when they hover over the option.
 */
export type SurveyOption = {
    /**
     * Label
     */
    label: string;
    /**
     * Value
     */
    value?: string | null;
    /**
     * Tip
     */
    tip?: string | null;
};

/**
 * SynthesizeRequest
 */
export type SynthesizeRequest = {
    /**
     * Answering Model
     */
    answering_model?: string | null;
    /**
     * N Interviews
     */
    n_interviews: number;
    language?: LanguageCode;
    /**
     * Delay Before Answers
     */
    delay_before_answers?: [
        number,
        number
    ] | null;
};

/**
 * TestSetupCreate
 */
export type TestSetupCreate = {
    /**
     * Name
     */
    name?: string | null;
    type: TestType;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Last Updated
     */
    last_updated?: string | null;
    language?: LanguageCode;
    /**
     * N Interviews
     */
    n_interviews?: number;
    /**
     * Answering Model
     */
    answering_model?: string | null;
    /**
     * Delay Before Answers
     */
    delay_before_answers?: [
        number,
        number
    ] | null;
};

/**
 * TestSetupPublic
 */
export type TestSetupPublic = {
    /**
     * Name
     */
    name?: string | null;
    type: TestType;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Last Updated
     */
    last_updated?: string | null;
    language?: LanguageCode;
    /**
     * N Interviews
     */
    n_interviews?: number;
    /**
     * Answering Model
     */
    answering_model?: string | null;
    /**
     * Delay Before Answers
     */
    delay_before_answers?: [
        number,
        number
    ] | null;
    /**
     * N Runs
     */
    n_runs: number;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    background_info?: BackgroundInfoOptionsOutput | null;
    /**
     * Fixed Answers
     */
    fixed_answers?: Array<string> | null;
};

/**
 * TestType
 */
export type TestType = 'shuffled_ai' | 'fixed_ai' | 'fixed_answers';

/**
 * TimedMessage
 *
 * A message that is displayed to the interviewee after a certain amount of time
 */
export type TimedMessage = {
    /**
     * Message
     *
     * The message to display
     */
    message: string;
    /**
     * Time
     *
     * The time in seconds to wait before displaying the message
     */
    time: number;
    /**
     * Include In History
     *
     * Should the message be included in the interview history?
     */
    include_in_history?: boolean;
    /**
     * As Modal
     *
     * Should the message be shown as a modal? Defaults to False meaning it will be shown as a normal message.
     */
    as_modal?: boolean;
};

/**
 * UpdateBackgroundInfoRequest
 */
export type UpdateBackgroundInfoRequest = {
    background_info: BackgroundInfoOptionsInput;
};

/**
 * UpdateFixedAnswersRequest
 */
export type UpdateFixedAnswersRequest = {
    /**
     * Answers
     */
    answers: Array<string>;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Last Active
     */
    last_active?: string;
    /**
     * Last Login
     */
    last_login?: string;
    scope?: Scope;
    /**
     * Invite Token
     */
    invite_token?: string | 'test' | null;
    /**
     * Research Consent
     */
    research_consent?: boolean;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Last Active
     */
    last_active: string;
    /**
     * Last Login
     */
    last_login: string;
    scope?: Scope;
    /**
     * Id
     */
    id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VisualConfig
 */
export type VisualConfig = {
    /**
     * Model
     */
    model?: string;
    /**
     * Temperature
     */
    temperature?: number;
    lang?: LanguageCode;
    /**
     * Include
     */
    include?: boolean;
};

/**
 * Welcome
 */
export type Welcome = {
    /**
     * Title
     */
    title: string;
    /**
     * Text
     */
    text: string;
    /**
     * Email
     */
    email: string;
    /**
     * Video File Name
     */
    video_file_name?: string | null;
    /**
     * With Id
     */
    with_id?: boolean;
};

/**
 * Body_upload_image
 */
export type FastapiCompatV2BodyUploadImage = {
    /**
     * Primer
     */
    primer: string;
    /**
     * Description
     */
    description: string;
    /**
     * Alt
     */
    alt: string;
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_image
 */
export type FastapiCompatV2BodyUploadImage2 = {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Interview Id
     */
    interview_id: string;
    /**
     * File
     */
    file: Blob | File;
};

/**
 * OutgoingData
 */
export type OutgoingData = {
    /**
     * Type
     */
    type?: 'data';
    /**
     * Content
     */
    content?: string | null;
    /**
     * Interview Id
     */
    interview_id?: string | null;
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Progress
     */
    progress?: number | null;
    /**
     * Error
     */
    error?: 'InstanceInitializing' | null;
};

/**
 * OutgoingHistoryMessage
 */
export type OutgoingHistoryMessage = {
    /**
     * Content
     */
    content: string;
    role: MessageRole;
    /**
     * Interview Id
     */
    interview_id: string;
    /**
     * Message Id
     */
    message_id: number;
    /**
     * Include In History
     */
    include_in_history?: boolean;
    feedback?: Feedback | null;
    /**
     * Image
     */
    image?: Image | Array<Image> | null;
    survey_item?: SurveyItem | null;
    /**
     * Type
     */
    type?: 'history';
};

/**
 * OutgoingMessage
 */
export type OutgoingMessage = {
    /**
     * Content
     */
    content: string;
    role: MessageRole;
    /**
     * Interview Id
     */
    interview_id: string;
    /**
     * Message Id
     */
    message_id: number;
    /**
     * Include In History
     */
    include_in_history?: boolean;
    feedback?: Feedback | null;
    /**
     * Image
     */
    image?: Image | Array<Image> | null;
    survey_item?: SurveyItem | null;
    /**
     * Type
     */
    type?: 'message';
    /**
     * Can Answer
     */
    can_answer?: boolean;
    /**
     * User Image
     */
    user_image?: boolean;
    /**
     * Progress
     */
    progress?: number | null;
};

/**
 * ReceivedData
 */
export type ReceivedData = {
    /**
     * Type
     */
    type: 'message' | 'image';
    message_type?: MessageType | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * File
     */
    file?: string | null;
};

export type GetAnalysisCategoriesData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/analysis/categories';
};

export type GetAnalysisCategoriesErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisCategoriesError = GetAnalysisCategoriesErrors[keyof GetAnalysisCategoriesErrors];

export type GetAnalysisCategoriesResponses = {
    /**
     * Response Get Analysis Categories
     *
     * Successful Response
     */
    200: Array<AnalysisCategoryPublic>;
};

export type GetAnalysisCategoriesResponse = GetAnalysisCategoriesResponses[keyof GetAnalysisCategoriesResponses];

export type CreateAnalysisCategoryData = {
    body: AnalysisCategoryCreate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/analysis/categories';
};

export type CreateAnalysisCategoryErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAnalysisCategoryError = CreateAnalysisCategoryErrors[keyof CreateAnalysisCategoryErrors];

export type CreateAnalysisCategoryResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteAnalysisCategoryData = {
    body?: never;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/analysis/categories/{category_id}';
};

export type DeleteAnalysisCategoryErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnalysisCategoryError = DeleteAnalysisCategoryErrors[keyof DeleteAnalysisCategoryErrors];

export type DeleteAnalysisCategoryResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMessageAnnotationsData = {
    body?: never;
    path: {
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/api/messages/{message_id}/annotations';
};

export type GetMessageAnnotationsErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMessageAnnotationsError = GetMessageAnnotationsErrors[keyof GetMessageAnnotationsErrors];

export type GetMessageAnnotationsResponses = {
    /**
     * Response Get Message Annotations
     *
     * Successful Response
     */
    200: Array<MessageAnnotationPublic>;
};

export type GetMessageAnnotationsResponse = GetMessageAnnotationsResponses[keyof GetMessageAnnotationsResponses];

export type AddMessageAnnotationData = {
    body: MessageAnnotationCreate;
    path: {
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/api/messages/{message_id}/annotations';
};

export type AddMessageAnnotationErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMessageAnnotationError = AddMessageAnnotationErrors[keyof AddMessageAnnotationErrors];

export type AddMessageAnnotationResponses = {
    /**
     * Successful Response
     */
    200: MessageAnnotationPublic;
};

export type AddMessageAnnotationResponse = AddMessageAnnotationResponses[keyof AddMessageAnnotationResponses];

export type DeleteMessageAnnotationData = {
    body?: never;
    path: {
        /**
         * Annotation Id
         */
        annotation_id: string;
    };
    query?: never;
    url: '/api/analysis/annotations/{annotation_id}';
};

export type DeleteMessageAnnotationErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMessageAnnotationError = DeleteMessageAnnotationErrors[keyof DeleteMessageAnnotationErrors];

export type DeleteMessageAnnotationResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateMessageAnnotationData = {
    body: MessageAnnotationCreate;
    path: {
        /**
         * Annotation Id
         */
        annotation_id: string;
    };
    query?: never;
    url: '/api/analysis/annotations/{annotation_id}';
};

export type UpdateMessageAnnotationErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMessageAnnotationError = UpdateMessageAnnotationErrors[keyof UpdateMessageAnnotationErrors];

export type UpdateMessageAnnotationResponses = {
    /**
     * Successful Response
     */
    200: MessageAnnotationPublic;
};

export type UpdateMessageAnnotationResponse = UpdateMessageAnnotationResponses[keyof UpdateMessageAnnotationResponses];

export type GetCollaboratorsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Project Id
         */
        project_id: string;
    };
    url: '/api/dashboard/collaborators';
};

export type GetCollaboratorsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCollaboratorsError = GetCollaboratorsErrors[keyof GetCollaboratorsErrors];

export type GetCollaboratorsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetExperimentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/experiments';
};

export type GetExperimentsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateExperimentData = {
    body: ExperimentCreate;
    path?: never;
    query?: never;
    url: '/api/experiments';
};

export type CreateExperimentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateExperimentError = CreateExperimentErrors[keyof CreateExperimentErrors];

export type CreateExperimentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteExperimentData = {
    body?: never;
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/api/experiments/{experiment_id}';
};

export type DeleteExperimentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteExperimentError = DeleteExperimentErrors[keyof DeleteExperimentErrors];

export type DeleteExperimentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GenerateExperimentQrData = {
    body?: never;
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/api/experiments/{experiment_id}/qr.png';
};

export type GenerateExperimentQrErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateExperimentQrError = GenerateExperimentQrErrors[keyof GenerateExperimentQrErrors];

export type GenerateExperimentQrResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteFolderData = {
    body: ProjectFolderDelete;
    path?: never;
    query?: never;
    url: '/api/folders';
};

export type DeleteFolderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFolderError = DeleteFolderErrors[keyof DeleteFolderErrors];

export type DeleteFolderResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetFoldersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/folders';
};

export type GetFoldersResponses = {
    /**
     * Response Get Folders
     *
     * Successful Response
     */
    200: Array<ProjectFolderWithProjects>;
};

export type GetFoldersResponse = GetFoldersResponses[keyof GetFoldersResponses];

export type EditFolderData = {
    body: ProjectFolderEdit;
    path?: never;
    query?: never;
    url: '/api/folders';
};

export type EditFolderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditFolderError = EditFolderErrors[keyof EditFolderErrors];

export type EditFolderResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateFolderData = {
    body: ProjectFolderCreate;
    path?: never;
    query?: never;
    url: '/api/folders';
};

export type CreateFolderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFolderError = CreateFolderErrors[keyof CreateFolderErrors];

export type CreateFolderResponses = {
    /**
     * Successful Response
     */
    200: ProjectFolderPublic;
};

export type CreateFolderResponse = CreateFolderResponses[keyof CreateFolderResponses];

export type GetProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type GetProjectsResponses = {
    /**
     * Response Get Projects
     *
     * Successful Response
     */
    200: Array<ProjectPublic>;
};

export type GetProjectsResponse = GetProjectsResponses[keyof GetProjectsResponses];

export type CreateProjectData = {
    body: CreateProjectRequest;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type CreateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetProjectIdsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/ids';
};

export type GetProjectIdsResponses = {
    /**
     * Response Get Project Ids
     *
     * Successful Response
     */
    200: Array<string>;
};

export type GetProjectIdsResponse = GetProjectIdsResponses[keyof GetProjectIdsResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}';
};

export type DeleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}';
};

export type GetProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type CloneProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/clone';
};

export type CloneProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloneProjectError = CloneProjectErrors[keyof CloneProjectErrors];

export type CloneProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type CloneProjectResponse = CloneProjectResponses[keyof CloneProjectResponses];

export type RemoveProjectLanguagesData = {
    body: LanguageCode;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/available_languages';
};

export type RemoveProjectLanguagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveProjectLanguagesError = RemoveProjectLanguagesErrors[keyof RemoveProjectLanguagesErrors];

export type RemoveProjectLanguagesResponses = {
    /**
     * Response Remove Project Languages
     *
     * Successful Response
     */
    200: Array<LanguageDict>;
};

export type RemoveProjectLanguagesResponse = RemoveProjectLanguagesResponses[keyof RemoveProjectLanguagesResponses];

export type AddProjectLanguagesData = {
    body: LanguageCode;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/available_languages';
};

export type AddProjectLanguagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddProjectLanguagesError = AddProjectLanguagesErrors[keyof AddProjectLanguagesErrors];

export type AddProjectLanguagesResponses = {
    /**
     * Response Add Project Languages
     *
     * Successful Response
     */
    200: Array<LanguageDict>;
};

export type AddProjectLanguagesResponse = AddProjectLanguagesResponses[keyof AddProjectLanguagesResponses];

export type ChangeProjectStatusData = {
    body: ProjectStatusChangeRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/status';
};

export type ChangeProjectStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeProjectStatusError = ChangeProjectStatusErrors[keyof ChangeProjectStatusErrors];

export type ChangeProjectStatusResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChangeProjectTitleData = {
    body: ProjectTitleUpdateRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/title';
};

export type ChangeProjectTitleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeProjectTitleError = ChangeProjectTitleErrors[keyof ChangeProjectTitleErrors];

export type ChangeProjectTitleResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetGuideData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        lang: LanguageCode;
    };
    query?: never;
    url: '/api/projects/{project_id}/{lang}/guide';
};

export type GetGuideErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGuideError = GetGuideErrors[keyof GetGuideErrors];

export type GetGuideResponses = {
    /**
     * Successful Response
     */
    200: InterviewGuideOutput;
};

export type GetGuideResponse = GetGuideResponses[keyof GetGuideResponses];

export type CreateGuideData = {
    body: InterviewGuideInput;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        lang: LanguageCode;
    };
    query?: never;
    url: '/api/projects/{project_id}/{lang}/guide';
};

export type CreateGuideErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGuideError = CreateGuideErrors[keyof CreateGuideErrors];

export type CreateGuideResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GenerateGuideData = {
    body: InterviewGuideGenerationPromptRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        lang: LanguageCode;
    };
    query?: never;
    url: '/api/projects/{project_id}/{lang}/guide/generate';
};

export type GenerateGuideErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateGuideError = GenerateGuideErrors[keyof GenerateGuideErrors];

export type GenerateGuideResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadImageData = {
    body: FastapiCompatV2BodyUploadImage;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/image';
};

export type UploadImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadImageError = UploadImageErrors[keyof UploadImageErrors];

export type UploadImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetInterviewAgentsData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        lang: LanguageCode;
    };
    query?: never;
    url: '/api/projects/{project_id}/{lang}/agents';
};

export type GetInterviewAgentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInterviewAgentsError = GetInterviewAgentsErrors[keyof GetInterviewAgentsErrors];

export type GetInterviewAgentsResponses = {
    /**
     * Successful Response
     */
    200: AgentConfigsOutput;
};

export type GetInterviewAgentsResponse = GetInterviewAgentsResponses[keyof GetInterviewAgentsResponses];

export type CreateInterviewAgentsData = {
    body: AgentConfigsInput;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        lang: LanguageCode;
    };
    query?: never;
    url: '/api/projects/{project_id}/{lang}/agents';
};

export type CreateInterviewAgentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInterviewAgentsError = CreateInterviewAgentsErrors[keyof CreateInterviewAgentsErrors];

export type CreateInterviewAgentsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetInterviewConfigData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/config';
};

export type GetInterviewConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInterviewConfigError = GetInterviewConfigErrors[keyof GetInterviewConfigErrors];

export type GetInterviewConfigResponses = {
    /**
     * Successful Response
     */
    200: InterviewConfig;
};

export type GetInterviewConfigResponse = GetInterviewConfigResponses[keyof GetInterviewConfigResponses];

export type CreateInterviewConfigData = {
    body: InterviewConfig;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/config';
};

export type CreateInterviewConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInterviewConfigError = CreateInterviewConfigErrors[keyof CreateInterviewConfigErrors];

export type CreateInterviewConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPromptsData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        lang: LanguageCode;
    };
    query?: never;
    url: '/api/projects/{project_id}/{lang}/prompts';
};

export type GetPromptsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPromptsError = GetPromptsErrors[keyof GetPromptsErrors];

export type GetPromptsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreatePromptsData = {
    body: PromptsUpdateRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        lang: LanguageCode;
    };
    query?: never;
    url: '/api/projects/{project_id}/{lang}/prompts';
};

export type CreatePromptsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePromptsError = CreatePromptsErrors[keyof CreatePromptsErrors];

export type CreatePromptsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetConsentData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        language: LanguageCode;
    };
    query?: never;
    url: '/api/projects/{project_id}/guide/consent/{language}';
};

export type GetConsentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConsentError = GetConsentErrors[keyof GetConsentErrors];

export type GetConsentResponses = {
    /**
     * Response Get Consent
     *
     * Successful Response
     */
    200: Consent | null;
};

export type GetConsentResponse = GetConsentResponses[keyof GetConsentResponses];

export type CreateConsentData = {
    body: Consent;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        language: LanguageCode;
    };
    query?: never;
    url: '/api/projects/{project_id}/guide/consent/{language}';
};

export type CreateConsentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConsentError = CreateConsentErrors[keyof CreateConsentErrors];

export type CreateConsentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetWelcomeData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        language: LanguageCode;
    };
    query?: never;
    url: '/api/projects/{project_id}/guide/welcome/{language}';
};

export type GetWelcomeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWelcomeError = GetWelcomeErrors[keyof GetWelcomeErrors];

export type GetWelcomeResponses = {
    /**
     * Response Get Welcome
     *
     * Successful Response
     */
    200: Welcome | null;
};

export type GetWelcomeResponse = GetWelcomeResponses[keyof GetWelcomeResponses];

export type CreateWelcomeData = {
    body: BodyCreateWelcome;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        language: LanguageCode;
    };
    query?: never;
    url: '/api/projects/{project_id}/guide/welcome/{language}';
};

export type CreateWelcomeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWelcomeError = CreateWelcomeErrors[keyof CreateWelcomeErrors];

export type CreateWelcomeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteInterviewsData = {
    body: DeleteInterviewRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/interviews';
};

export type DeleteInterviewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteInterviewsError = DeleteInterviewsErrors[keyof DeleteInterviewsErrors];

export type DeleteInterviewsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetInterviewsData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Synthetic
         */
        synthetic?: boolean | null;
        /**
         * Test
         */
        test?: boolean | null;
        /**
         * Created At
         */
        created_at?: string | null;
        /**
         * Completed
         */
        completed?: boolean | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Column
         */
        column?: string;
        /**
         * Order
         */
        order?: 'asc' | 'desc';
    };
    url: '/api/projects/{project_id}/interviews';
};

export type GetInterviewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInterviewsError = GetInterviewsErrors[keyof GetInterviewsErrors];

export type GetInterviewsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportMessagesData = {
    body: ExportMessagesRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Interview Id
         */
        interview_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/interviews/{interview_id}/messages';
};

export type ExportMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportMessagesError = ExportMessagesErrors[keyof ExportMessagesErrors];

export type ExportMessagesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GenerateProjectQrData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/qr.png';
};

export type GenerateProjectQrErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateProjectQrError = GenerateProjectQrErrors[keyof GenerateProjectQrErrors];

export type GenerateProjectQrResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetBackgroundInfoData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Test Id
         */
        test_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/tests/{test_id}/background_info';
};

export type GetBackgroundInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBackgroundInfoError = GetBackgroundInfoErrors[keyof GetBackgroundInfoErrors];

export type GetBackgroundInfoResponses = {
    /**
     * Successful Response
     */
    200: BackgroundInfoOptionsOutput;
};

export type GetBackgroundInfoResponse = GetBackgroundInfoResponses[keyof GetBackgroundInfoResponses];

export type UpdateBackgroundInfoData = {
    body: UpdateBackgroundInfoRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Test Id
         */
        test_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/tests/{test_id}/background_info';
};

export type UpdateBackgroundInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBackgroundInfoError = UpdateBackgroundInfoErrors[keyof UpdateBackgroundInfoErrors];

export type UpdateBackgroundInfoResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetFixedAnswersData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Test Id
         */
        test_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/tests/{test_id}/fixed_answers';
};

export type GetFixedAnswersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFixedAnswersError = GetFixedAnswersErrors[keyof GetFixedAnswersErrors];

export type GetFixedAnswersResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateFixedAnswersData = {
    body: UpdateFixedAnswersRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Test Id
         */
        test_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/tests/{test_id}/fixed_answers';
};

export type UpdateFixedAnswersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateFixedAnswersError = UpdateFixedAnswersErrors[keyof UpdateFixedAnswersErrors];

export type UpdateFixedAnswersResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTestSetupsData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/tests';
};

export type GetTestSetupsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTestSetupsError = GetTestSetupsErrors[keyof GetTestSetupsErrors];

export type GetTestSetupsResponses = {
    /**
     * Response Get Test Setups
     *
     * Successful Response
     */
    200: Array<TestSetupPublic>;
};

export type GetTestSetupsResponse = GetTestSetupsResponses[keyof GetTestSetupsResponses];

export type CreateTestSetupData = {
    body: TestSetupCreate;
    path?: never;
    query?: never;
    url: '/api/projects/{project_id}/tests';
};

export type CreateTestSetupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTestSetupError = CreateTestSetupErrors[keyof CreateTestSetupErrors];

export type CreateTestSetupResponses = {
    /**
     * Successful Response
     */
    200: TestSetupPublic;
};

export type CreateTestSetupResponse = CreateTestSetupResponses[keyof CreateTestSetupResponses];

export type AddIntervieweeData = {
    body: IntervieweeCreate;
    path?: never;
    query?: never;
    url: '/api/interviewee';
};

export type AddIntervieweeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddIntervieweeError = AddIntervieweeErrors[keyof AddIntervieweeErrors];

export type AddIntervieweeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTestStatusData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Test Id
         */
        test_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/tests/{test_id}/status';
};

export type GetTestStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTestStatusError = GetTestStatusErrors[keyof GetTestStatusErrors];

export type GetTestStatusResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RunSyntheticTestData = {
    body: SynthesizeRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Test Id
         */
        test_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/tests/{test_id}/run';
};

export type RunSyntheticTestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunSyntheticTestError = RunSyntheticTestErrors[keyof RunSyntheticTestErrors];

export type RunSyntheticTestResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RenderConsentModalData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/consent/render';
};

export type RenderConsentModalErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenderConsentModalError = RenderConsentModalErrors[keyof RenderConsentModalErrors];

export type RenderConsentModalResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SetConsentData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/welcome/render';
};

export type SetConsentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetConsentError = SetConsentErrors[keyof SetConsentErrors];

export type SetConsentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateInterviewData = {
    body?: never;
    headers?: {
        /**
         * User-Agent
         */
        'user-agent'?: string | null;
        /**
         * X-Real-Ip
         */
        'X-Real-IP'?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        lang: LanguageCode;
    };
    query?: {
        interviewer?: Interviewer;
        /**
         * Synthetic
         */
        synthetic?: boolean;
        /**
         * Fixed Answers
         */
        fixed_answers?: boolean;
    };
    url: '/api/projects/{project_id}/{lang}/interviews';
};

export type CreateInterviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInterviewError = CreateInterviewErrors[keyof CreateInterviewErrors];

export type CreateInterviewResponses = {
    /**
     * Response Create Interview
     *
     * Successful Response
     */
    200: string;
};

export type CreateInterviewResponse = CreateInterviewResponses[keyof CreateInterviewResponses];

export type PutFeedbackData = {
    body: MessageFeedback;
    path?: never;
    query?: never;
    url: '/api/feedback';
};

export type PutFeedbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutFeedbackError = PutFeedbackErrors[keyof PutFeedbackErrors];

export type PutFeedbackResponses = {
    /**
     * Successful Response
     */
    200: MessageFeedback;
};

export type PutFeedbackResponse = PutFeedbackResponses[keyof PutFeedbackResponses];

export type UploadImage2Data = {
    body: FastapiCompatV2BodyUploadImage2;
    path?: never;
    query?: never;
    url: '/api/image';
};

export type UploadImage2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadImage2Error = UploadImage2Errors[keyof UploadImage2Errors];

export type UploadImage2Responses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginData2 = {
    body: LoginData;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type RegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RequestAccessData = {
    body: AccessRequestCreate;
    path?: never;
    query?: never;
    url: '/api/request-access';
};

export type RequestAccessErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestAccessError = RequestAccessErrors[keyof RequestAccessErrors];

export type RequestAccessResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExitData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/exit';
};

export type ExitResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/refresh';
};

export type RefreshTokenResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAccessRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/admin/access-requests';
};

export type GetAccessRequestsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProccessAccessRequestsData = {
    body: AccessRequestsProcessRequest;
    path?: never;
    query?: never;
    url: '/api/admin/admin/access-requests/process';
};

export type ProccessAccessRequestsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProccessAccessRequestsError = ProccessAccessRequestsErrors[keyof ProccessAccessRequestsErrors];

export type ProccessAccessRequestsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProxyToEc2ManagerData = {
    body?: never;
    path: {
        /**
         * Full Path
         */
        full_path: string;
    };
    query?: never;
    url: '/api/admin/aws/ec2/{full_path}';
};

export type ProxyToEc2ManagerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyToEc2ManagerError = ProxyToEc2ManagerErrors[keyof ProxyToEc2ManagerErrors];

export type ProxyToEc2ManagerResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProxyToEc2Manager2Data = {
    body?: never;
    path: {
        /**
         * Full Path
         */
        full_path: string;
    };
    query?: never;
    url: '/api/admin/aws/ec2/{full_path}';
};

export type ProxyToEc2Manager2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyToEc2Manager2Error = ProxyToEc2Manager2Errors[keyof ProxyToEc2Manager2Errors];

export type ProxyToEc2Manager2Responses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProxyToEc2Manager3Data = {
    body?: never;
    path: {
        /**
         * Full Path
         */
        full_path: string;
    };
    query?: never;
    url: '/api/admin/aws/ec2/{full_path}';
};

export type ProxyToEc2Manager3Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyToEc2Manager3Error = ProxyToEc2Manager3Errors[keyof ProxyToEc2Manager3Errors];

export type ProxyToEc2Manager3Responses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProxyToEc2Manager4Data = {
    body?: never;
    path: {
        /**
         * Full Path
         */
        full_path: string;
    };
    query?: never;
    url: '/api/admin/aws/ec2/{full_path}';
};

export type ProxyToEc2Manager4Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyToEc2Manager4Error = ProxyToEc2Manager4Errors[keyof ProxyToEc2Manager4Errors];

export type ProxyToEc2Manager4Responses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProxyToEc2Manager5Data = {
    body?: never;
    path: {
        /**
         * Full Path
         */
        full_path: string;
    };
    query?: never;
    url: '/api/admin/aws/ec2/{full_path}';
};

export type ProxyToEc2Manager5Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyToEc2Manager5Error = ProxyToEc2Manager5Errors[keyof ProxyToEc2Manager5Errors];

export type ProxyToEc2Manager5Responses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/models';
};

export type GetModelsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetLanguagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/languages';
};

export type GetLanguagesResponses = {
    /**
     * Response Get Languages
     *
     * Successful Response
     */
    200: Array<LanguageDict>;
};

export type GetLanguagesResponse = GetLanguagesResponses[keyof GetLanguagesResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ActiveWebsocketsWsConnectionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ws/connections';
};

export type ActiveWebsocketsWsConnectionsGetResponses = {
    /**
     * Response Active Websockets Ws Connections Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ActiveWebsocketsWsConnectionsGetResponse = ActiveWebsocketsWsConnectionsGetResponses[keyof ActiveWebsocketsWsConnectionsGetResponses];

export type ConnectWsConnectProjectIdInterviewIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Interview Id
         */
        interview_id: string;
    };
    query?: never;
    url: '/ws/connect/{project_id}/{interview_id}';
};

export type ConnectWsConnectProjectIdInterviewIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConnectWsConnectProjectIdInterviewIdGetError = ConnectWsConnectProjectIdInterviewIdGetErrors[keyof ConnectWsConnectProjectIdInterviewIdGetErrors];

export type ConnectWsConnectProjectIdInterviewIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BroadcastWsBroadcastPostData = {
    body: Broadcast;
    path?: never;
    query?: never;
    url: '/ws/broadcast';
};

export type BroadcastWsBroadcastPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BroadcastWsBroadcastPostError = BroadcastWsBroadcastPostErrors[keyof BroadcastWsBroadcastPostErrors];

export type BroadcastWsBroadcastPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
