// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AccessRequestCreate
 */
export const zAccessRequestCreate = z.object({
    name: z.string(),
    email: z.email(),
    organization: z.string().nullish(),
    message: z.string().nullish()
});

/**
 * AccessRequestsDeleteRequest
 */
export const zAccessRequestsDeleteRequest = z.object({
    ids: z.array(z.string())
});

/**
 * AdminNoteUpdate
 */
export const zAdminNoteUpdate = z.object({
    note: z.string().nullish()
});

/**
 * AgentConfig
 */
export const zAgentConfig = z.object({
    model: z.string().optional().default('openrouter:openai/gpt-oss-120b'),
    temperature: z.number().gte(0).lte(2).optional().default(0.7),
    include: z.boolean().optional().default(true)
});

/**
 * AnnotationType
 */
export const zAnnotationType = z.enum(['tag', 'score']);

/**
 * AnalysisCategoryCreate
 */
export const zAnalysisCategoryCreate = z.object({
    project_id: z.string(),
    name: z.string(),
    description: z.string().nullish(),
    type: zAnnotationType,
    color: z.string(),
    min_value: z.int().nullish(),
    max_value: z.int().nullish()
});

/**
 * AnalysisCategoryPublic
 */
export const zAnalysisCategoryPublic = z.object({
    project_id: z.string(),
    name: z.string(),
    description: z.string().nullish(),
    type: zAnnotationType,
    color: z.string(),
    min_value: z.int().nullish(),
    max_value: z.int().nullish(),
    id: z.string(),
    created_at: z.iso.datetime()
});

/**
 * AnnotationValueCreate
 */
export const zAnnotationValueCreate = z.object({
    category_id: z.string(),
    value_int: z.int()
});

/**
 * AnnotationValuePublic
 */
export const zAnnotationValuePublic = z.object({
    category_id: z.string(),
    value_int: z.int(),
    id: z.string()
});

/**
 * AnswerLength
 */
export const zAnswerLength = z.enum([
    'short',
    'medium',
    'long'
]);

/**
 * Body_create_welcome
 */
export const zBodyCreateWelcome = z.object({
    title: z.string(),
    text: z.string(),
    email: z.email(),
    video: z.string().nullish()
});

/**
 * Body_upload_audio
 */
export const zBodyUploadAudio = z.object({
    project_id: z.string(),
    interview_id: z.string(),
    file: z.string()
});

/**
 * Body_upload_image
 */
export const zBodyUploadImage = z.object({
    primer: z.string(),
    description: z.string(),
    alt: z.string(),
    file: z.string()
});

/**
 * Body_upload_interview_image
 */
export const zBodyUploadInterviewImage = z.object({
    project_id: z.string(),
    interview_id: z.string(),
    file: z.string()
});

/**
 * Body_upload_participant_email_attachments
 */
export const zBodyUploadParticipantEmailAttachments = z.object({
    files: z.array(z.string())
});

/**
 * Body_upload_participant_reminder_email_attachments
 */
export const zBodyUploadParticipantReminderEmailAttachments = z.object({
    files: z.array(z.string())
});

/**
 * Body_upload_participants
 */
export const zBodyUploadParticipants = z.object({
    file: z.string()
});

/**
 * CheckboxItem
 */
export const zCheckboxItem = z.object({
    type: z.literal('checkbox').optional().default('checkbox'),
    required: z.boolean().optional().default(true),
    options: z.array(z.string()),
    with_other: z.boolean().optional().default(false)
});

/**
 * CollaboratorRole
 */
export const zCollaboratorRole = z.enum([
    'viewer',
    'annotator',
    'editor',
    'admin'
]);

/**
 * Collaborator
 */
export const zCollaborator = z.object({
    email: z.email(),
    role: zCollaboratorRole
});

/**
 * CollaboratorCreate
 */
export const zCollaboratorCreate = z.object({
    role: zCollaboratorRole,
    email: z.email()
});

/**
 * CommunicationTrait
 */
export const zCommunicationTrait = z.object({
    length: zAnswerLength,
    style: z.string(),
    tone: z.string()
});

/**
 * CommunicationTraits
 */
export const zCommunicationTraits = z.object({
    length: z.array(z.union([zAnswerLength, z.string()])),
    style: z.array(z.string()),
    tone: z.array(z.string())
});

/**
 * BackgroundInfoOptions
 *
 * Dataclass representing the possible values for the background info of the synthetic agents
 */
export const zBackgroundInfoOptionsInput = z.object({
    names_gender: z.array(z.tuple([z.string(), z.string()])),
    age_range: z.tuple([z.int(), z.int()]).optional().default([18, 80]),
    educations: z.array(z.string()),
    occupations: z.array(z.string()),
    locations: z.array(z.string()),
    personalities: z.array(z.string()),
    communication_traits: zCommunicationTraits,
    extra_traits: z.union([
        z.array(z.record(z.string(), z.string())),
        z.array(z.string())
    ]).nullish(),
    refusal_rate: z.tuple([z.number(), z.number()]).nullish()
});

/**
 * BackgroundInfoOptions
 *
 * Dataclass representing the possible values for the background info of the synthetic agents
 */
export const zBackgroundInfoOptionsOutput = z.object({
    names_gender: z.array(z.tuple([z.string(), z.string()])),
    age_range: z.tuple([z.int(), z.int()]).optional().default([18, 80]),
    educations: z.array(z.string()),
    occupations: z.array(z.string()),
    locations: z.array(z.string()),
    personalities: z.array(z.string()),
    communication_traits: zCommunicationTraits,
    extra_traits: z.union([
        z.array(z.record(z.string(), z.string())),
        z.array(z.string())
    ]).nullish(),
    refusal_rate: z.tuple([z.number(), z.number()]).nullish()
});

/**
 * ComponentChange
 *
 * One component release that landed in a platform release.
 *
 * `groups` maps a changelog section ("Features", "Bug Fixes", ...) to its
 * entries, as generated by git-cliff and published in the component's GitHub
 * Release. Only user-visible sections are carried here, and a release with
 * nothing user-visible is omitted entirely — the version it shipped is already
 * recorded in the manifest's component fields.
 */
export const zComponentChange = z.object({
    version: z.string(),
    date: z.iso.datetime().nullish(),
    groups: z.record(z.string(), z.array(z.string())).optional()
});

/**
 * ConditionAction
 */
export const zConditionAction = z.enum([
    'end_interview',
    'skip_section',
    'skip_question',
    'skip_probes'
]);

/**
 * ConditionEvaluation
 *
 * A single evaluation check with an optional operator to combine with the next evaluation.
 *
 * For "A AND B OR C", create:
 * [
 * ConditionEvaluation(trigger_value="A", combine_next="AND"),
 * ConditionEvaluation(trigger_value="B", combine_next="OR"),
 * ConditionEvaluation(trigger_value="C"),
 * ]
 *
 * For numeric comparisons (e.g., age >= 18):
 * ConditionEvaluation(trigger_value="18", comparison_operator=">=")
 */
export const zConditionEvaluation = z.object({
    trigger_value: z.union([
        z.string(),
        z.int(),
        z.number()
    ]),
    comparison_operator: z.enum([
        '==',
        '<',
        '<=',
        '>',
        '>='
    ]).optional(),
    combine_next: z.enum(['AND', 'OR']).nullish()
});

/**
 * ConditionTrigger
 */
export const zConditionTrigger = z.enum(['match', 'classification']);

/**
 * Consent
 */
export const zConsent = z.object({
    title: z.string(),
    text: z.string()
});

/**
 * DailyInterviewCount
 *
 * Count of interviews created per day.
 */
export const zDailyInterviewCount = z.object({
    date: z.iso.date(),
    count: z.int(),
    completed_count: z.int()
});

/**
 * DateItem
 */
export const zDateItem = z.object({
    type: z.literal('date').optional().default('date'),
    required: z.boolean().optional().default(true),
    min: z.string().nullish().default(null),
    max: z.string().nullish().default(null)
});

/**
 * DatetimeItem
 */
export const zDatetimeItem = z.object({
    type: z.literal('datetime').optional().default('datetime'),
    required: z.boolean().optional().default(true),
    min: z.string().nullish().default(null),
    max: z.string().nullish().default(null)
});

/**
 * DeleteAccountRequest
 */
export const zDeleteAccountRequest = z.object({
    password: z.string()
});

/**
 * DeleteInterviewRequest
 */
export const zDeleteInterviewRequest = z.object({
    interview_ids: z.array(z.string())
});

/**
 * DeleteParticipantsRequest
 */
export const zDeleteParticipantsRequest = z.object({
    participant_ids: z.array(z.string())
});

/**
 * DropoutPoint
 *
 * Count of dropouts at a specific question.
 */
export const zDropoutPoint = z.object({
    main_question: z.int().nullable(),
    sub_question: z.int().nullable(),
    count: z.int()
});

/**
 * ErrorResponse
 */
export const zErrorResponse = z.object({
    detail: z.string()
});

/**
 * ExperimentProjectCreate
 *
 * Input model for adding a project to an experiment.
 */
export const zExperimentProjectCreate = z.object({
    project_id: z.string(),
    weight: z.number().nullish()
});

/**
 * ExperimentCreate
 */
export const zExperimentCreate = z.object({
    title: z.string(),
    projects: z.array(zExperimentProjectCreate)
});

/**
 * ExperimentProjectPublic
 *
 * Public model for experiment-project association.
 */
export const zExperimentProjectPublic = z.object({
    id: z.string(),
    project_id: z.string(),
    weight: z.number().nullish(),
    added_at: z.iso.datetime()
});

/**
 * ExportMessagesRequest
 */
export const zExportMessagesRequest = z.object({
    interview_ids: z.array(z.string()),
    format: z.enum(['csv', 'xlsx']).optional()
});

/**
 * ExportParticipantsRequest
 */
export const zExportParticipantsRequest = z.object({
    participant_ids: z.array(z.string()).nullish()
});

/**
 * ExternalParam
 *
 * Definition of a single external URL query parameter.
 */
export const zExternalParam = z.object({
    name: z.string().regex(/^[a-zA-Z_][a-zA-Z0-9_]*$/),
    type: z.enum([
        'str',
        'int',
        'float',
        'bool',
        'enum'
    ]),
    required: z.boolean().optional().default(true),
    default: z.union([
        z.string(),
        z.int(),
        z.number(),
        z.boolean()
    ]).nullish(),
    options: z.array(z.string()).nullish(),
    description: z.string().nullish()
});

/**
 * ExternalParamsRequest
 */
export const zExternalParamsRequest = z.object({
    params: z.array(zExternalParam)
});

/**
 * Feedback
 */
export const zFeedback = z.enum(['positive', 'negative']);

/**
 * FilteredMessagesRequest
 */
export const zFilteredMessagesRequest = z.object({
    category_ids: z.array(z.string()).nullish(),
    search_text: z.string().nullish(),
    exact_match: z.boolean().optional().default(false),
    case_sensitive: z.boolean().optional().default(false),
    questions: z.array(z.tuple([z.int(), z.int()])).nullish(),
    include_previous_on_user: z.boolean().optional().default(true)
});

/**
 * GeneratedQuestions
 */
export const zGeneratedQuestions = z.object({
    n: z.int().optional().default(0),
    max_probes_n: z.int().nullish(),
    max_probes_time: z.int().nullish()
});

/**
 * GitHashes
 */
export const zGitHashes = z.object({
    core_lib: z.string(),
    backend: z.string(),
    frontend: z.string()
});

/**
 * Highlight
 *
 * One user-facing change in a platform release.
 *
 * Deliberately carries no component or version: a single change often spans
 * backend and frontend, and a user has no use for either fact. `notes` keeps
 * the per-component provenance for support and debugging.
 */
export const zHighlight = z.object({
    kind: z.enum([
        'new',
        'improved',
        'fixed'
    ]),
    title: z.string(),
    body: z.string().nullish()
});

/**
 * HistogramBucket
 *
 * A value-count pair for histogram use.
 */
export const zHistogramBucket = z.object({
    value: z.int(),
    count: z.int(),
    label: z.string()
});

/**
 * Image
 *
 * An image to show the interviewee
 */
export const zImage = z.object({
    type: z.enum([
        'audio',
        'image',
        'video'
    ]).optional(),
    name: z.string(),
    data: z.string().nullable(),
    primer: z.string().nullish().default(null),
    description: z.string(),
    alt: z.string()
});

/**
 * InterviewDurationStats
 *
 * Statistics about interview duration (time spent).
 */
export const zInterviewDurationStats = z.object({
    min_seconds: z.int(),
    max_seconds: z.int(),
    avg_seconds: z.number(),
    sum_seconds: z.number()
});

/**
 * InterviewGuideGenerationRequest
 */
export const zInterviewGuideGenerationRequest = z.object({
    prompt: z.string()
});

/**
 * InterviewMessage
 */
export const zInterviewMessage = z.object({
    message: z.string()
});

/**
 * InterviewStatus
 */
export const zInterviewStatus = z.enum([
    'active',
    'inactive',
    'completed'
]);

/**
 * InterviewStatusCount
 *
 * Count of interviews by status.
 */
export const zInterviewStatusCount = z.object({
    status: zInterviewStatus,
    count: z.int()
});

/**
 * InterviewSubject
 *
 * Dataclass representing the interview subject
 */
export const zInterviewSubject = z.object({
    name: z.string(),
    age: z.int(),
    gender: z.string(),
    education: z.string(),
    occupation: z.string(),
    location: z.string(),
    personality: z.string(),
    communication_trait: zCommunicationTrait,
    extra_traits: z.union([
        z.record(z.string(), z.string()),
        z.string()
    ]).nullish(),
    refusal_rate: z.number().gte(0).lte(1).optional().default(0)
});

/**
 * InterviewTimeOfDayCount
 */
export const zInterviewTimeOfDayCount = z.object({
    time: z.string(),
    count: z.int()
});

/**
 * InterviewType
 */
export const zInterviewType = z.enum([
    'manual_test',
    'synthetic_test',
    'distributed'
]);

/**
 * IntervieweeCreate
 */
export const zIntervieweeCreate = z.object({
    interview_id: z.string(),
    interview_subject: z.union([
        zInterviewSubject,
        z.string()
    ])
});

/**
 * Interviewer
 */
export const zInterviewer = z.enum(['human', 'ai']);

/**
 * InvitationsDeleteRequest
 */
export const zInvitationsDeleteRequest = z.object({
    ids: z.array(z.string())
});

export const zLanguageCode = z.string().length(2);

/**
 * Body_add_project_language
 */
export const zBodyAddProjectLanguage = z.object({
    language: zLanguageCode,
    translate: z.boolean().optional().default(true)
});

/**
 * CreateProjectRequest
 */
export const zCreateProjectRequest = z.object({
    title: z.string(),
    default_language: zLanguageCode
});

/**
 * LanguageDict
 */
export const zLanguageDict = z.object({
    name: z.string(),
    code: zLanguageCode
});

/**
 * LikertItem
 */
export const zLikertItem = z.object({
    type: z.literal('likert').optional().default('likert'),
    required: z.boolean().optional().default(true),
    options: z.array(z.string()),
    ui: z.enum(['radio', 'slider']).optional()
});

/**
 * LoginData
 */
export const zLoginData = z.object({
    email: z.string(),
    password: z.string(),
    extended: z.boolean().optional().default(false)
});

/**
 * MediaUploadResponse
 */
export const zMediaUploadResponse = z.object({
    message: z.string(),
    filename: z.string()
});

/**
 * MessageAnnotationCreate
 */
export const zMessageAnnotationCreate = z.object({
    message_id: z.string(),
    user_id: z.string(),
    comment: z.string().nullish(),
    values: z.array(zAnnotationValueCreate)
});

/**
 * MessageAnnotationPublic
 */
export const zMessageAnnotationPublic = z.object({
    message_id: z.string(),
    user_id: z.string(),
    comment: z.string().nullish(),
    id: z.string(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    values: z.array(zAnnotationValuePublic)
});

/**
 * MessageCountStats
 *
 * Statistics about message counts per interview.
 */
export const zMessageCountStats = z.object({
    min_messages: z.int(),
    max_messages: z.int(),
    avg_messages: z.number(),
    sum_messages: z.int()
});

/**
 * MessageFeedbackResponse
 */
export const zMessageFeedbackResponse = z.object({
    interview_id: z.string(),
    project_id: z.string(),
    message_id: z.int(),
    feedback: zFeedback.nullable()
});

/**
 * MessageRole
 */
export const zMessageRole = z.enum([
    'system',
    'assistant',
    'user'
]);

/**
 * MessageType
 */
export const zMessageType = z.enum([
    'text',
    'image',
    'audio',
    'custom_token',
    'survey_item'
]);

/**
 * MonitoringStats
 *
 * Aggregated monitoring statistics for a project.
 */
export const zMonitoringStats = z.object({
    total_interviews: z.int(),
    completion_rate: z.number(),
    interviews_by_status: z.array(zInterviewStatusCount),
    interviews_over_time: z.array(zDailyInterviewCount),
    interviews_by_time_of_day: z.array(zInterviewTimeOfDayCount),
    duration_stats: zInterviewDurationStats.nullable(),
    message_count_stats: zMessageCountStats.nullable(),
    duration_histogram: z.array(zHistogramBucket),
    message_count_histogram: z.array(zHistogramBucket),
    message_length_histogram: z.array(zHistogramBucket),
    dropout_stats: z.array(zDropoutPoint)
});

/**
 * MoveProjectRequest
 */
export const zMoveProjectRequest = z.object({
    folder_id: z.string()
});

/**
 * NewsletterRequest
 */
export const zNewsletterRequest = z.object({
    email: z.email()
});

/**
 * NumberItem
 */
export const zNumberItem = z.object({
    type: z.literal('number').optional().default('number'),
    required: z.boolean().optional().default(true),
    min: z.union([
        z.int(),
        z.number()
    ]).nullish().default(null),
    max: z.union([
        z.int(),
        z.number()
    ]).nullish().default(null),
    step: z.union([
        z.int(),
        z.number()
    ]).nullish().default(1)
});

/**
 * ParticipantCreate
 */
export const zParticipantCreate = z.object({
    name: z.string().nullish(),
    email: z.email().nullish(),
    pid: z.string().nullish(),
    participating: z.boolean().optional().default(true),
    lang: zLanguageCode.nullish()
});

/**
 * ParticipantEmailAttachment
 */
export const zParticipantEmailAttachment = z.object({
    filename: z.string(),
    size: z.int(),
    content_type: z.string().nullish()
});

/**
 * ParticipantEmailTemplateRequest
 */
export const zParticipantEmailTemplateRequest = z.object({
    subject: z.string().nullish(),
    template: z.string().nullish()
});

/**
 * ParticipantPublic
 */
export const zParticipantPublic = z.object({
    name: z.string().nullish(),
    email: z.email().nullish(),
    pid: z.string(),
    participating: z.boolean().optional().default(true),
    lang: zLanguageCode.nullish(),
    id: z.string(),
    project_id: z.string(),
    participant_id: z.string(),
    folder_id: z.string(),
    created_at: z.iso.datetime(),
    latest_interview_at: z.iso.datetime().nullish(),
    latest_interview_status: zInterviewStatus.nullish()
});

/**
 * PlatformRelease
 *
 * What the app shows a user: no components, no versions, no hashes.
 */
export const zPlatformRelease = z.object({
    platform_version: z.string(),
    released_at: z.iso.datetime(),
    highlights: z.array(zHighlight)
});

/**
 * ProbingContext
 */
export const zProbingContext = z.enum(['section', 'question']);

/**
 * ProbingPromptPreview
 *
 * Rendered probing-agent prompts with the project's editable slots injected.
 *
 * Interview-time context (transcript, framing, etc.) is shown as labelled
 * placeholders since those values only exist while an interview is running.
 */
export const zProbingPromptPreview = z.object({
    system: z.string(),
    instruction: z.string()
});

/**
 * ProbingPromptSlots
 *
 * User-editable regions of the probing agent's system and instruction prompts.
 *
 * Each field is an override: when left as ``None`` the corresponding default
 * from ``DEFAULT_PROBING_SLOTS`` is used at render time, so improvements to the
 * defaults flow through to projects that have not customized that slot.
 */
export const zProbingPromptSlots = z.object({
    persona: z.string().nullish(),
    question_qualities: z.array(z.string()).nullish(),
    guidelines: z.array(z.string()).nullish(),
    instructions: z.array(z.string()).nullish()
});

/**
 * ProbingAgentConfig
 */
export const zProbingAgentConfig = z.object({
    model: z.string().optional().default('openrouter:openai/gpt-oss-120b'),
    temperature: z.number().gte(0).lte(2).optional().default(0.7),
    include: z.boolean().optional().default(true),
    few_shot_examples: z.array(z.string()).nullish(),
    prompt_slots: zProbingPromptSlots.optional()
});

/**
 * ProbingStrategy
 */
export const zProbingStrategy = z.enum([
    'standard',
    'dice_master_to_one_probe',
    'dice_ensemble_to_master_probe',
    'dice_master_to_ensemble_to_one_probe'
]);

/**
 * InterviewConfig
 */
export const zInterviewConfig = z.object({
    with_consent: z.boolean().optional().default(true),
    with_welcome: z.boolean().optional().default(true),
    with_audio: z.boolean().optional().default(false),
    probing_strategy: z.array(zProbingStrategy).optional()
});

/**
 * ProjectFolderCreate
 */
export const zProjectFolderCreate = z.object({
    title: z.string(),
    folder_collaborations: z.array(zCollaborator).optional().default([])
});

/**
 * ProjectFolderEdit
 */
export const zProjectFolderEdit = z.object({
    title: z.string()
});

/**
 * ProjectLanguage
 *
 * A language a project has a localization for.
 *
 * Same shape as the library's `LanguageDict` plus whether it is the
 * project's default. `LanguageDict` itself stays free of the flag: it comes
 * straight out of the shared `LANGUAGES` constant and knows nothing about
 * projects.
 */
export const zProjectLanguage = z.object({
    name: z.string(),
    code: zLanguageCode,
    is_default: z.boolean()
});

/**
 * ProjectStatus
 */
export const zProjectStatus = z.enum(['active', 'inactive']);

/**
 * ExperimentPublic
 */
export const zExperimentPublic = z.object({
    id: z.string(),
    title: z.string(),
    user_id: z.string(),
    created_at: z.iso.datetime(),
    status: zProjectStatus.optional().default('active'),
    projects: z.array(zExperimentProjectPublic).optional().default([])
});

/**
 * ProjectStatusChangeRequest
 */
export const zProjectStatusChangeRequest = z.object({
    status: zProjectStatus
});

/**
 * ProjectTitleUpdateRequest
 */
export const zProjectTitleUpdateRequest = z.object({
    title: z.string()
});

/**
 * QuestionBase
 *
 * A question that can be asked to the interviewee
 */
export const zQuestionBase = z.object({
    description: z.string().nullish(),
    main_question: z.string(),
    probes: z.array(z.string()).nullish(),
    max_probes_n: z.int().gte(0).nullish().default(3),
    max_probes_time: z.number().gt(0).nullish()
});

/**
 * QuestionContext
 *
 * The index of a question in a section
 * section [int]: The index of the section
 * question [int]: The index of the question
 * part
 */
export const zQuestionContext = z.object({
    section: z.int(),
    question: z.int(),
    part: z.enum([
        'main',
        'probes',
        'both'
    ]).optional()
});

/**
 * Condition
 *
 * Create a condition that must be met to ask a question
 */
export const zCondition = z.object({
    question_context: zQuestionContext,
    evaluation: z.array(zConditionEvaluation),
    negated: z.boolean().optional().default(false),
    trigger_type: zConditionTrigger.optional().default('match'),
    combine_next: z.enum(['AND', 'OR']).nullish()
});

/**
 * Conditions
 */
export const zConditionsInput = z.object({
    conditions: z.array(zCondition),
    action: zConditionAction
});

/**
 * Conditions
 */
export const zConditionsOutput = z.object({
    conditions: z.array(zCondition),
    action: zConditionAction
});

/**
 * QuestionGenerationRequest
 */
export const zQuestionGenerationRequest = z.object({
    prompt: z.string(),
    section_idx: z.int(),
    max_probes_n: z.int().nullish(),
    max_probes_time: z.int().nullish()
});

export const zQuestionIndex = z.tuple([z.int(), z.int()]);

/**
 * QuestionSection
 *
 * A section of questions that all revolve around the same topic
 */
export const zQuestionSection = z.object({
    description: z.string(),
    questions: z.array(zQuestionBase),
    shuffle: z.boolean().optional().default(false),
    ai_generated_questions: zGeneratedQuestions.optional().default({ n: 0 })
});

/**
 * QuestionSectionGenerationRequest
 */
export const zQuestionSectionGenerationRequest = z.object({
    prompt: z.string()
});

/**
 * RadioItem
 */
export const zRadioItem = z.object({
    type: z.literal('radio').optional().default('radio'),
    required: z.boolean().optional().default(true),
    options: z.array(z.string()),
    with_other: z.boolean().optional().default(false)
});

/**
 * Reference
 *
 * Create a reference to a previous answer, useful when refering back to a
 * previous answer, eg. an answer to a survey item. If used, the main question
 * must contains an empty `{}` as a placeholder for the referred answer.
 */
export const zReference = z.object({
    question_index: zQuestionIndex
});

/**
 * ReleaseNotes
 *
 * Component changes between the previously deployed platform release and this one.
 *
 * A component that did not move between deploys has an empty list. Note that
 * `core_lib` tracks the version the backend actually depends on (read from its
 * uv.lock), which lags the lib repo's own latest tag whenever the backend has
 * not yet bumped its pin.
 */
export const zReleaseNotes = z.object({
    core_lib: z.array(zComponentChange).optional(),
    backend: z.array(zComponentChange).optional(),
    frontend: z.array(zComponentChange).optional()
});

/**
 * PlatformManifest
 */
export const zPlatformManifest = z.object({
    platform_version: z.string(),
    core_lib: z.string(),
    backend: z.string(),
    frontend: z.string(),
    build_time: z.iso.datetime(),
    git: zGitHashes,
    notes: zReleaseNotes.nullish(),
    highlights: z.array(zHighlight).nullish()
});

/**
 * ResendVerificationRequest
 */
export const zResendVerificationRequest = z.object({
    email: z.email()
});

/**
 * Scope
 */
export const zScope = z.enum([
    'admin',
    'user',
    'demo',
    'guest'
]);

/**
 * AccessRequestsProcessRequest
 */
export const zAccessRequestsProcessRequest = z.object({
    ids: z.array(z.string()),
    scopes: z.array(zScope),
    action: z.enum(['approve', 'deny'])
});

/**
 * SecurityConfig
 */
export const zSecurityConfig = z.object({
    model: z.string().optional().default('openrouter:openai/gpt-oss-120b'),
    temperature: z.number().gte(0).lte(2).optional().default(0.7),
    include: z.boolean().optional().default(false),
    sensitive_subjects: z.array(z.unknown()).nullish()
});

/**
 * SendParticipantEmailRequest
 */
export const zSendParticipantEmailRequest = z.object({
    participant_ids: z.array(z.string()).nullish()
});

/**
 * SendParticipantEmailResponse
 */
export const zSendParticipantEmailResponse = z.object({
    sent: z.array(z.string()),
    skipped: z.array(z.string())
});

/**
 * SliderItem
 */
export const zSliderItem = z.object({
    type: z.literal('slider').optional().default('slider'),
    required: z.boolean().optional().default(true),
    min: z.union([
        z.int(),
        z.number()
    ]),
    max: z.union([
        z.int(),
        z.number()
    ]),
    min_label: z.string().nullish().default(null),
    max_label: z.string().nullish().default(null),
    step: z.union([
        z.int(),
        z.number()
    ]).nullish().default(1)
});

/**
 * SpeechRequest
 */
export const zSpeechRequest = z.object({
    message_id: z.int()
});

/**
 * SynthesizeRequest
 */
export const zSynthesizeRequest = z.object({
    answering_model: z.string().nullish(),
    n_interviews: z.int().gte(1).lte(100),
    language: zLanguageCode.optional().default('EN'),
    delay_before_answers: z.tuple([z.number(), z.number()]).nullish()
});

/**
 * TestType
 */
export const zTestType = z.enum([
    'shuffled_ai',
    'fixed_ai',
    'fixed_answers'
]);

/**
 * CreateInterviewRequest
 */
export const zCreateInterviewRequest = z.object({
    interviewer: zInterviewer.optional().default('ai'),
    interview_type: zInterviewType.optional().default('distributed'),
    test_run_id: z.string().nullish(),
    experiment_id: z.string().nullish(),
    synthetic_test_type: zTestType.nullish(),
    participant_id: z.string().nullish(),
    pid: z.string().nullish(),
    external_params: z.record(z.string(), z.unknown()).nullish(),
    referer: z.string().nullish()
});

/**
 * TestSetupCreate
 */
export const zTestSetupCreate = z.object({
    name: z.string().nullish(),
    type: zTestType,
    project_id: z.string(),
    answering_model: z.string().optional().default('openrouter:openai/gpt-oss-120b'),
    last_updated: z.iso.datetime().nullish(),
    language: zLanguageCode.optional().default('EN'),
    n_interviews: z.int().optional().default(5),
    delay_before_answers: z.tuple([z.number(), z.number()]).nullish()
});

/**
 * TestSetupPublic
 */
export const zTestSetupPublic = z.object({
    name: z.string().nullish(),
    type: zTestType,
    project_id: z.string(),
    answering_model: z.string().optional().default('openrouter:openai/gpt-oss-120b'),
    last_updated: z.iso.datetime().nullish(),
    language: zLanguageCode.optional().default('EN'),
    n_interviews: z.int().optional().default(5),
    delay_before_answers: z.tuple([z.number(), z.number()]).nullish(),
    n_runs: z.int(),
    id: z.string(),
    created_at: z.iso.datetime(),
    background_info: zBackgroundInfoOptionsOutput.nullish(),
    fixed_answers: z.array(z.string()).nullish(),
    fixed_personas: z.array(z.string()).nullish()
});

/**
 * TimeDelta
 */
export const zTimeDelta = z.object({
    days: z.int().optional().default(0),
    seconds: z.int().optional().default(0),
    microseconds: z.int().optional().default(0),
    milliseconds: z.int().optional().default(0),
    minutes: z.int().optional().default(0),
    hours: z.int().optional().default(0),
    weeks: z.int().optional().default(0)
});

/**
 * InvitationCreate
 */
export const zInvitationCreate = z.object({
    expires_at: z.iso.datetime().nullish(),
    reuseable: z.boolean().optional().default(false),
    user_scope: zScope.optional().default('user'),
    user_expires: z.union([
        z.iso.datetime(),
        zTimeDelta
    ]).nullish(),
    title: z.string().nullish(),
    access_request_id: z.string().nullish()
});

/**
 * InvitationPublic
 */
export const zInvitationPublic = z.object({
    expires_at: z.iso.datetime().nullish(),
    reuseable: z.boolean().optional().default(false),
    user_scope: zScope.optional().default('user'),
    user_expires: z.union([
        z.iso.datetime(),
        zTimeDelta
    ]).nullish(),
    title: z.string().nullish(),
    access_request_id: z.string().nullish(),
    id: z.string(),
    email: z.string().nullable(),
    invitation_link: z.string().readonly()
});

/**
 * TimeItem
 */
export const zTimeItem = z.object({
    type: z.literal('time').optional().default('time'),
    required: z.boolean().optional().default(true),
    min: z.string().nullish().default(null),
    max: z.string().nullish().default(null)
});

/**
 * MessagePublic
 */
export const zMessagePublic = z.object({
    message_id: z.int(),
    content: z.string(),
    role: zMessageRole,
    interview_id: z.string(),
    project_id: z.string(),
    message_type: zMessageType.optional().default('text'),
    section: z.int().nullish(),
    main_question: z.int().nullish(),
    sub_question: z.int().nullish(),
    is_introduction: z.boolean().optional().default(false),
    outro: z.boolean().optional().default(false),
    timed: z.boolean().optional().default(false),
    can_answer: z.boolean().optional().default(true),
    include_in_history: z.boolean().optional().default(true),
    attachment: z.string().nullish(),
    audio_file: z.string().nullish(),
    feedback: zFeedback.nullish(),
    created_at: z.iso.datetime(),
    image: z.union([
        zImage,
        z.array(zImage)
    ]).nullish(),
    survey_item: z.union([
        zRadioItem,
        zCheckboxItem,
        zLikertItem,
        zSliderItem,
        zNumberItem,
        zDateItem,
        zDatetimeItem,
        zTimeItem
    ]).nullish(),
    skipped_by_condition: z.boolean().optional().default(false),
    id: z.string(),
    annotations: z.array(zMessageAnnotationPublic).optional().default([]),
    interview_type: zInterviewType
});

/**
 * InterviewSummaryPublic
 */
export const zInterviewSummaryPublic = z.object({
    id: z.string(),
    language: zLanguageCode.optional().default('EN'),
    interviewer: zInterviewer.optional().default('ai'),
    status: zInterviewStatus,
    type: zInterviewType,
    created_at: z.iso.datetime(),
    last_updated: z.iso.datetime().nullish(),
    total_time_spent: z.int().optional().default(0),
    n_messages: z.int(),
    messages: z.array(zMessagePublic),
    test_name: z.string().nullish()
});

/**
 * PaginatedResponse[InterviewSummaryPublic]
 */
export const zPaginatedResponseInterviewSummaryPublic = z.object({
    total: z.int(),
    items: z.array(zInterviewSummaryPublic)
});

/**
 * Question
 *
 * A question that can be asked to the interviewee
 */
export const zQuestionInput = z.object({
    description: z.string().nullish(),
    main_question: z.string(),
    probes: z.array(z.string()).nullish(),
    max_probes_n: z.int().gte(0).nullish().default(3),
    max_probes_time: z.number().gt(0).nullish(),
    survey_item: z.union([
        zRadioItem,
        zCheckboxItem,
        zLikertItem,
        zSliderItem,
        zNumberItem,
        zDateItem,
        zDatetimeItem,
        zTimeItem
    ]).nullish(),
    can_answer: z.boolean().optional().default(true),
    alternative_main_questions: z.array(z.string()).nullish(),
    check_if_answered: z.boolean().optional().default(false),
    check_if_exhausted: z.boolean().optional().default(false),
    can_skip: z.boolean().optional().default(true),
    shuffle: z.boolean().optional().default(false),
    create_segue: z.boolean().optional().default(false),
    exclude_from_history: z.boolean().optional().default(false),
    references: z.array(zReference).nullish(),
    image: zImage.nullish(),
    user_image: z.boolean().optional().default(false),
    conditions: zConditionsInput.nullish(),
    probing_context: zProbingContext.nullish(),
    index: zQuestionIndex.nullish()
});

/**
 * Question
 *
 * A question that can be asked to the interviewee
 */
export const zQuestionOutput = z.object({
    description: z.string().nullish(),
    main_question: z.string(),
    probes: z.array(z.string()).nullish(),
    max_probes_n: z.int().gte(0).nullish().default(3),
    max_probes_time: z.number().gt(0).nullish(),
    survey_item: z.union([
        zRadioItem,
        zCheckboxItem,
        zLikertItem,
        zSliderItem,
        zNumberItem,
        zDateItem,
        zDatetimeItem,
        zTimeItem
    ]).nullish(),
    can_answer: z.boolean().optional().default(true),
    alternative_main_questions: z.array(z.string()).nullish(),
    check_if_answered: z.boolean().optional().default(false),
    check_if_exhausted: z.boolean().optional().default(false),
    can_skip: z.boolean().optional().default(true),
    shuffle: z.boolean().optional().default(false),
    create_segue: z.boolean().optional().default(false),
    exclude_from_history: z.boolean().optional().default(false),
    references: z.array(zReference).nullish(),
    image: zImage.nullish(),
    user_image: z.boolean().optional().default(false),
    conditions: zConditionsOutput.nullish(),
    probing_context: zProbingContext.nullish(),
    index: zQuestionIndex.nullish()
});

/**
 * QuestionSection[Question]
 */
export const zQuestionSectionQuestionInput = z.object({
    description: z.string(),
    questions: z.array(zQuestionInput),
    shuffle: z.boolean().optional().default(false),
    ai_generated_questions: zGeneratedQuestions.optional().default({ n: 0 })
});

/**
 * QuestionSection[Question]
 */
export const zQuestionSectionQuestionOutput = z.object({
    description: z.string(),
    questions: z.array(zQuestionOutput),
    shuffle: z.boolean().optional().default(false),
    ai_generated_questions: zGeneratedQuestions.optional().default({ n: 0 })
});

/**
 * TimedMessage
 *
 * A message that is displayed to the interviewee after a certain amount of time
 */
export const zTimedMessage = z.object({
    message: z.string(),
    time: z.int(),
    include_in_history: z.boolean().optional().default(false),
    as_modal: z.boolean().optional().default(false)
});

/**
 * InterviewGuide
 */
export const zInterviewGuideInput = z.object({
    framing: z.string().optional().default(''),
    introduction: z.string().optional().default(''),
    question_sections: z.array(zQuestionSectionQuestionInput).optional(),
    outro: z.string().nullish(),
    extra_variables: z.array(z.string()).optional(),
    timed_messages: z.array(zTimedMessage).nullish(),
    ai_generated_sections: z.int().optional().default(0)
});

/**
 * AssistanceChatRequest
 */
export const zAssistanceChatRequest = z.object({
    prompt: z.string(),
    guide: zInterviewGuideInput
});

/**
 * InterviewGuide
 */
export const zInterviewGuideOutput = z.object({
    framing: z.string().optional().default(''),
    introduction: z.string().optional().default(''),
    question_sections: z.array(zQuestionSectionQuestionOutput).optional(),
    outro: z.string().nullish(),
    extra_variables: z.array(z.string()).optional(),
    timed_messages: z.array(zTimedMessage).nullish(),
    ai_generated_sections: z.int().optional().default(0)
});

/**
 * UpdateBackgroundInfoRequest
 */
export const zUpdateBackgroundInfoRequest = z.object({
    background_info: zBackgroundInfoOptionsInput
});

/**
 * UpdateEmailRequest
 */
export const zUpdateEmailRequest = z.object({
    password: z.string(),
    new_email: z.email()
});

/**
 * UpdateFixedAnswersRequest
 */
export const zUpdateFixedAnswersRequest = z.object({
    answers: z.array(z.string())
});

/**
 * UpdateFixedPersonasRequest
 */
export const zUpdateFixedPersonasRequest = z.object({
    fixed_personas: z.array(z.string())
});

/**
 * UpdatePasswordRequest
 */
export const zUpdatePasswordRequest = z.object({
    current_password: z.string(),
    new_password: z.string().min(8)
});

/**
 * UserAdmin
 */
export const zUserAdmin = z.object({
    email: z.email(),
    first_name: z.string(),
    last_name: z.string().nullish(),
    created_at: z.iso.datetime(),
    last_active: z.iso.datetime(),
    last_login: z.iso.datetime(),
    scope: zScope.optional().default('user'),
    id: z.string(),
    invitation_title: z.string().nullish(),
    expires_at: z.iso.datetime().nullish(),
    with_demo_features: z.boolean(),
    organization: z.string().nullish(),
    access_request_message: z.string().nullish(),
    admin_note: z.string().nullish(),
    admin_note_updated_at: z.iso.datetime().nullish(),
    two_factor_enabled: z.boolean().optional().default(true)
});

/**
 * UserCreateRequest
 *
 * API request model for user registration.
 */
export const zUserCreateRequest = z.object({
    email: z.email(),
    first_name: z.string(),
    last_name: z.string().nullish(),
    created_at: z.iso.datetime().optional(),
    last_active: z.iso.datetime().optional(),
    last_login: z.iso.datetime().optional(),
    scope: zScope.optional().default('user'),
    invite_token: z.union([
        z.string(),
        z.string()
    ]).nullable(),
    research_consent: z.boolean().optional().default(false),
    password: z.string().min(8)
});

/**
 * UserPublic
 */
export const zUserPublic = z.object({
    email: z.email(),
    first_name: z.string(),
    last_name: z.string().nullish(),
    created_at: z.iso.datetime(),
    last_active: z.iso.datetime(),
    last_login: z.iso.datetime(),
    scope: zScope.optional().default('user'),
    id: z.string(),
    invitation_title: z.string().nullish(),
    expires_at: z.iso.datetime().nullish(),
    with_demo_features: z.boolean(),
    organization: z.string().nullish()
});

/**
 * CollaboratorPublic
 */
export const zCollaboratorPublic = z.object({
    role: zCollaboratorRole,
    id: z.string(),
    user: zUserPublic,
    added_at: z.iso.datetime()
});

/**
 * ProjectFolderPublic
 */
export const zProjectFolderPublic = z.object({
    title: z.string(),
    id: z.string(),
    collaborators: z.array(zCollaboratorPublic).optional().default([])
});

/**
 * ProjectPublic
 */
export const zProjectPublic = z.object({
    id: z.string(),
    title: z.string(),
    created_at: z.iso.datetime(),
    last_updated: z.iso.datetime().nullish(),
    status: zProjectStatus.optional().default('active'),
    config: zInterviewConfig,
    external_params: z.array(zExternalParam).nullish(),
    owner_id: z.string(),
    n_interviews: z.int().nullish(),
    available_languages: z.array(zProjectLanguage).nullish(),
    tests: z.array(zTestSetupPublic).nullish(),
    owner: zUserPublic
});

/**
 * ProjectFolderWithProjects
 */
export const zProjectFolderWithProjects = z.object({
    title: z.string(),
    id: z.string(),
    collaborators: z.array(zCollaboratorPublic).optional().default([]),
    projects: z.array(zProjectPublic)
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * VerifyEmailRequest
 */
export const zVerifyEmailRequest = z.object({
    token: z.string()
});

/**
 * VerifyLoginCodeRequest
 */
export const zVerifyLoginCodeRequest = z.object({
    email: z.string(),
    code: z.string(),
    extended: z.boolean().optional().default(false)
});

/**
 * VisualConfig
 */
export const zVisualConfig = z.object({
    model: z.string().optional().default('llava'),
    temperature: z.number().gte(0).lte(2).optional().default(0.7),
    include: z.boolean().optional().default(false)
});

/**
 * AgentConfigs
 */
export const zAgentConfigsInput = z.object({
    probing: zProbingAgentConfig.optional(),
    classification: zAgentConfig.optional(),
    guide: zAgentConfig.optional(),
    history: zAgentConfig.optional(),
    security: zSecurityConfig.optional(),
    answering: zAgentConfig.optional(),
    reformulation: zAgentConfig.optional(),
    visual: zVisualConfig.optional()
});

/**
 * AgentConfigs
 */
export const zAgentConfigsOutput = z.object({
    probing: zProbingAgentConfig.optional(),
    classification: zAgentConfig.optional(),
    guide: zAgentConfig.optional(),
    history: zAgentConfig.optional(),
    security: zSecurityConfig.optional(),
    answering: zAgentConfig.optional(),
    reformulation: zAgentConfig.optional(),
    visual: zVisualConfig.optional()
});

/**
 * Welcome
 */
export const zWelcome = z.object({
    title: z.string(),
    text: z.string(),
    email: z.email(),
    video_file_name: z.string().nullish(),
    with_id: z.boolean().optional().default(true)
});

/**
 * _Unset
 */
export const zUnset = z.enum(['UNSET']);

/**
 * InvitationUpdate
 */
export const zInvitationUpdate = z.object({
    email: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET'),
    expires_at: z.union([
        z.iso.datetime(),
        zUnset
    ]).nullish().default('UNSET'),
    reuseable: z.union([
        z.boolean(),
        zUnset
    ]).optional().default('UNSET'),
    user_scope: z.union([
        zScope,
        zUnset
    ]).optional().default('UNSET'),
    user_expires: z.union([
        z.iso.datetime(),
        zTimeDelta,
        zUnset
    ]).nullish().default('UNSET'),
    title: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET')
});

/**
 * ParticipantUpdate
 */
export const zParticipantUpdate = z.object({
    name: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET'),
    email: z.union([
        z.email(),
        zUnset
    ]).nullish().default('UNSET'),
    pid: z.union([
        z.string(),
        zUnset
    ]).optional().default('UNSET'),
    participating: z.union([
        z.boolean(),
        zUnset
    ]).optional().default('UNSET')
});

/**
 * UserAdminUpdate
 */
export const zUserAdminUpdate = z.object({
    scope: z.union([
        zScope,
        zUnset
    ]).optional().default('UNSET'),
    with_demo_features: z.union([
        z.boolean(),
        zUnset
    ]).optional().default('UNSET'),
    organization: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET'),
    expires_at: z.union([
        z.iso.datetime(),
        zUnset
    ]).nullish().default('UNSET'),
    two_factor_enabled: z.union([
        z.boolean(),
        zUnset
    ]).optional().default('UNSET')
});

/**
 * UserSelfUpdate
 *
 * Profile fields a user may change on their own account.
 */
export const zUserSelfUpdate = z.object({
    first_name: z.union([
        z.string(),
        zUnset
    ]).optional().default('UNSET'),
    last_name: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET'),
    organization: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET')
});

/**
 * AuthToken
 */
export const zAuthToken = z.object({
    user_id: z.string(),
    scope: zScope
});

/**
 * ChatMessage
 *
 * Format of messages sent to the browser.
 */
export const zChatMessage = z.object({
    type: z.enum([
        'message',
        'question',
        'section'
    ]).optional(),
    role: z.enum(['user', 'model']),
    timestamp: z.string(),
    content: z.string()
});

/**
 * CustomToken
 */
export const zCustomToken = z.enum([
    '<|endofprobe|>',
    '<|endofsection|>',
    '<|endofinterview|>',
    '<|skipquestion|>',
    '<|skipsection|>',
    '<|noanswer|>',
    '<|restartinterview|>'
]);

/**
 * InterviewRole
 */
export const zInterviewRole = z.enum(['interviewer', 'respondent']);

/**
 * InterviewToken
 */
export const zInterviewToken = z.object({
    project_id: z.string(),
    interview_id: z.string(),
    interviewer: zInterviewer,
    role: zInterviewRole.optional().default('respondent')
});

/**
 * OutgoingData
 */
export const zOutgoingData = z.object({
    type: z.literal('data').optional().default('data'),
    content: z.string().nullish().default(null),
    progress: z.number().gte(0).lte(100).nullish().default(null),
    error: z.enum(['InstanceInitializing', 'InferenceError']).nullish().default(null)
});

/**
 * OutgoingHistoryMessage
 */
export const zOutgoingHistoryMessage = z.object({
    type: z.literal('history').optional().default('history'),
    content: z.string(),
    role: zMessageRole,
    message_id: z.int(),
    feedback: zFeedback.nullish().default(null),
    image: z.union([
        zImage,
        z.array(zImage)
    ]).nullish().default(null),
    survey_item: z.union([
        zRadioItem,
        zCheckboxItem,
        zLikertItem,
        zSliderItem,
        zNumberItem,
        zDateItem,
        zDatetimeItem,
        zTimeItem
    ]).nullish().default(null)
});

/**
 * OutgoingMessage
 */
export const zOutgoingMessage = z.object({
    type: z.literal('message').optional().default('message'),
    content: z.string(),
    role: zMessageRole,
    message_id: z.int(),
    feedback: zFeedback.nullish().default(null),
    image: z.union([
        zImage,
        z.array(zImage)
    ]).nullish().default(null),
    survey_item: z.union([
        zRadioItem,
        zCheckboxItem,
        zLikertItem,
        zSliderItem,
        zNumberItem,
        zDateItem,
        zDatetimeItem,
        zTimeItem
    ]).nullish().default(null),
    can_answer: z.boolean().optional().default(true),
    user_image: z.boolean().optional().default(false),
    progress: z.number().gte(0).lte(100).nullish().default(null),
    is_probe: z.boolean().optional().default(false)
});

/**
 * ReceivedData
 */
export const zReceivedData = z.object({
    type: z.enum([
        'message',
        'image',
        'audio'
    ]),
    message_type: zMessageType.nullish().default(null),
    content: z.string(),
    filename: z.string().nullish().default(null)
});

/**
 * InvitationPublic
 */
export const zInvitationPublicWritable = z.object({
    expires_at: z.iso.datetime().nullish(),
    reuseable: z.boolean().optional().default(false),
    user_scope: zScope.optional().default('user'),
    user_expires: z.union([
        z.iso.datetime(),
        zTimeDelta
    ]).nullish(),
    title: z.string().nullish(),
    access_request_id: z.string().nullish(),
    id: z.string(),
    email: z.string().nullable()
});

export const zGetAnalysisCategoriesData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Response Get Analysis Categories
 *
 * Successful Response
 */
export const zGetAnalysisCategoriesResponse = z.array(zAnalysisCategoryPublic);

export const zCreateAnalysisCategoryData = z.object({
    body: zAnalysisCategoryCreate,
    path: z.object({
        project_id: z.string()
    }),
    query: z.never().optional()
});

export const zDeleteAnalysisCategoryData = z.object({
    body: z.never().optional(),
    path: z.object({
        category_id: z.string()
    }),
    query: z.never().optional()
});

export const zUpdateAnalysisCategoryData = z.object({
    body: zAnalysisCategoryCreate,
    path: z.object({
        category_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUpdateAnalysisCategoryResponse = zAnalysisCategoryPublic;

export const zGetMessageAnnotationsData = z.object({
    body: z.never().optional(),
    path: z.object({
        message_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Response Get Message Annotations
 *
 * Successful Response
 */
export const zGetMessageAnnotationsResponse = z.array(zMessageAnnotationPublic);

export const zAddMessageAnnotationData = z.object({
    body: zMessageAnnotationCreate,
    path: z.object({
        message_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zAddMessageAnnotationResponse = zMessageAnnotationPublic;

export const zDeleteMessageAnnotationData = z.object({
    body: z.never().optional(),
    path: z.object({
        annotation_id: z.string()
    }),
    query: z.never().optional()
});

export const zUpdateMessageAnnotationData = z.object({
    body: zMessageAnnotationCreate,
    path: z.object({
        annotation_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUpdateMessageAnnotationResponse = zMessageAnnotationPublic;

export const zGetFilteredMessagesCountData = z.object({
    body: zFilteredMessagesRequest,
    path: z.object({
        project_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Response Get Filtered Messages Count
 *
 * Successful Response
 */
export const zGetFilteredMessagesCountResponse = z.int();

export const zGetFilteredMessagesData = z.object({
    body: zFilteredMessagesRequest,
    path: z.object({
        project_id: z.string()
    }),
    query: z.object({
        skip: z.int().optional().default(0),
        limit: z.int().optional().default(20)
    }).optional()
});

/**
 * Response Get Filtered Messages
 *
 * Successful Response
 */
export const zGetFilteredMessagesResponse = z.array(zMessagePublic);

export const zGetMessageContextBeforeData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string(),
        interview_id: z.string(),
        message_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Response Get Message Context Before
 *
 * Successful Response
 */
export const zGetMessageContextBeforeResponse = z.array(zMessagePublic);

export const zGetMessageContextAfterData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string(),
        interview_id: z.string(),
        message_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Response Get Message Context After
 *
 * Successful Response
 */
export const zGetMessageContextAfterResponse = z.array(zMessagePublic);

export const zGetProjectMonitoringStatsData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string()
    }),
    query: z.object({
        interview_types: z.array(zInterviewType).optional(),
        start_date: z.iso.datetime().nullish(),
        end_date: z.iso.datetime().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetProjectMonitoringStatsResponse = zMonitoringStats;

export const zResetSessionData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        lang: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetChatData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        lang: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zSendChatData = z.object({
    body: zAssistanceChatRequest,
    path: z.object({
        project_id: z.string().nullable(),
        lang: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetExperimentsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Get Experiments
 *
 * Successful Response
 */
export const zGetExperimentsResponse = z.array(zExperimentPublic);

export const zCreateExperimentData = z.object({
    body: zExperimentCreate,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zCreateExperimentResponse = zExperimentPublic;

export const zDeleteExperimentData = z.object({
    body: z.never().optional(),
    path: z.object({
        experiment_id: z.string()
    }),
    query: z.never().optional()
});

export const zGenerateExperimentQrData = z.object({
    body: z.never().optional(),
    path: z.object({
        experiment_id: z.string()
    }),
    query: z.never().optional()
});

export const zGetFoldersData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Get Folders
 *
 * Successful Response
 */
export const zGetFoldersResponse = z.array(zProjectFolderWithProjects);

export const zCreateFolderData = z.object({
    body: zProjectFolderCreate,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zCreateFolderResponse = zProjectFolderPublic;

export const zDeleteFolderData = z.object({
    body: z.never().optional(),
    path: z.object({
        folder_id: z.string().nullable()
    }),
    query: z.object({
        project_id: z.string().nullish()
    }).optional()
});

export const zEditFolderData = z.object({
    body: zProjectFolderEdit,
    path: z.object({
        folder_id: z.string().nullable()
    }),
    query: z.object({
        project_id: z.string().nullish()
    }).optional()
});

export const zRemoveCollaboratorData = z.object({
    body: z.never().optional(),
    path: z.object({
        folder_id: z.string().nullable()
    }),
    query: z.object({
        user_id: z.string(),
        project_id: z.string().nullish()
    })
});

export const zGetCollaboratorsData = z.object({
    body: z.never().optional(),
    path: z.object({
        folder_id: z.string().nullable()
    }),
    query: z.object({
        project_id: z.string().nullish()
    }).optional()
});

/**
 * Response Get Collaborators
 *
 * Successful Response
 */
export const zGetCollaboratorsResponse = z.array(zCollaboratorPublic);

export const zUpdateCollaboratorRoleData = z.object({
    body: z.never().optional(),
    path: z.object({
        folder_id: z.string().nullable()
    }),
    query: z.object({
        user_id: z.string(),
        role: zCollaboratorRole,
        project_id: z.string().nullish()
    })
});

/**
 * Successful Response
 */
export const zUpdateCollaboratorRoleResponse = zCollaboratorPublic;

export const zAddCollaboratorData = z.object({
    body: zCollaboratorCreate,
    path: z.object({
        folder_id: z.string().nullable()
    }),
    query: z.object({
        project_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zAddCollaboratorResponse = zCollaboratorPublic;

export const zCreateProjectData = z.object({
    body: zCreateProjectRequest,
    path: z.object({
        folder_id: z.string().nullable()
    }),
    query: z.object({
        project_id: z.string().nullish()
    }).optional()
});

export const zDeleteParticipantsData = z.object({
    body: zDeleteParticipantsRequest,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetParticipantsData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Get Participants
 *
 * Successful Response
 */
export const zGetParticipantsResponse = z.array(zParticipantPublic);

export const zAddParticipantData = z.object({
    body: zParticipantCreate,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zAddParticipantResponse = zParticipantPublic;

export const zDeleteParticipantData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        participant_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetParticipantData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        participant_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetParticipantResponse = zParticipantPublic;

export const zUpdateParticipantData = z.object({
    body: zParticipantUpdate,
    path: z.object({
        project_id: z.string().nullable(),
        participant_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zUpdateParticipantResponse = zParticipantPublic;

export const zExportParticipantsData = z.object({
    body: zExportParticipantsRequest,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zExportEmailBundleData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zExportEmailBundleResponse = z.string();

export const zOptOutData = z.object({
    body: z.string().nullish(),
    path: z.object({
        opt_out_token: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zOptOutResponse = zParticipantPublic;

export const zAddParticipantsData = z.object({
    body: z.array(zParticipantCreate),
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Add Participants
 *
 * Successful Response
 */
export const zAddParticipantsResponse = z.array(zParticipantPublic);

export const zUploadParticipantsData = z.object({
    body: zBodyUploadParticipants,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Upload Participants
 *
 * Successful Response
 */
export const zUploadParticipantsResponse = z.array(zParticipantPublic);

export const zGetParticipantEmailTemplateData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetParticipantEmailTemplateResponse = zParticipantEmailTemplateRequest;

export const zSetParticipantEmailTemplateData = z.object({
    body: zParticipantEmailTemplateRequest,
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zSetParticipantEmailTemplateResponse = zParticipantEmailTemplateRequest;

export const zListParticipantEmailAttachmentsData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response List Participant Email Attachments
 *
 * Successful Response
 */
export const zListParticipantEmailAttachmentsResponse = z.array(zParticipantEmailAttachment);

export const zUploadParticipantEmailAttachmentsData = z.object({
    body: zBodyUploadParticipantEmailAttachments,
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Upload Participant Email Attachments
 *
 * Successful Response
 */
export const zUploadParticipantEmailAttachmentsResponse = z.array(zParticipantEmailAttachment);

export const zDeleteParticipantEmailAttachmentData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2),
        filename: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Delete Participant Email Attachment
 *
 * Successful Response
 */
export const zDeleteParticipantEmailAttachmentResponse = z.array(zParticipantEmailAttachment);

export const zSendParticipantEmailsData = z.object({
    body: zSendParticipantEmailRequest,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zSendParticipantEmailsResponse = zSendParticipantEmailResponse;

export const zGetParticipantReminderEmailTemplateData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetParticipantReminderEmailTemplateResponse = zParticipantEmailTemplateRequest;

export const zSetParticipantReminderEmailTemplateData = z.object({
    body: zParticipantEmailTemplateRequest,
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zSetParticipantReminderEmailTemplateResponse = zParticipantEmailTemplateRequest;

export const zListParticipantReminderEmailAttachmentsData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response List Participant Reminder Email Attachments
 *
 * Successful Response
 */
export const zListParticipantReminderEmailAttachmentsResponse = z.array(zParticipantEmailAttachment);

export const zUploadParticipantReminderEmailAttachmentsData = z.object({
    body: zBodyUploadParticipantReminderEmailAttachments,
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Upload Participant Reminder Email Attachments
 *
 * Successful Response
 */
export const zUploadParticipantReminderEmailAttachmentsResponse = z.array(zParticipantEmailAttachment);

export const zDeleteParticipantReminderEmailAttachmentData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2),
        filename: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Delete Participant Reminder Email Attachment
 *
 * Successful Response
 */
export const zDeleteParticipantReminderEmailAttachmentResponse = z.array(zParticipantEmailAttachment);

export const zSendParticipantReminderEmailsData = z.object({
    body: zSendParticipantEmailRequest,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zSendParticipantReminderEmailsResponse = zSendParticipantEmailResponse;

export const zDeleteProjectData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetProjectData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetProjectResponse = zProjectPublic;

export const zCloneProjectData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zCloneProjectResponse = zProjectPublic;

export const zRemoveProjectLanguageData = z.object({
    body: zLanguageCode,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Remove Project Language
 *
 * Successful Response
 */
export const zRemoveProjectLanguageResponse = z.array(zProjectLanguage);

export const zGetProjectLanguagesData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Response Get Project Languages
 *
 * Successful Response
 */
export const zGetProjectLanguagesResponse = z.array(zProjectLanguage);

export const zAddProjectLanguageData = z.object({
    body: zBodyAddProjectLanguage,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Add Project Language
 *
 * Successful Response
 */
export const zAddProjectLanguageResponse = z.array(zProjectLanguage);

export const zSetDefaultLanguageData = z.object({
    body: zLanguageCode,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Set Default Language
 *
 * Successful Response
 */
export const zSetDefaultLanguageResponse = z.array(zProjectLanguage);

export const zChangeProjectStatusData = z.object({
    body: zProjectStatusChangeRequest,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zChangeProjectTitleData = z.object({
    body: zProjectTitleUpdateRequest,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zMoveProjectData = z.object({
    body: zMoveProjectRequest,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetGuideData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        lang: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetGuideResponse = zInterviewGuideOutput;

export const zCreateGuideData = z.object({
    body: zInterviewGuideInput,
    path: z.object({
        project_id: z.string().nullable(),
        lang: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGenerateGuideData = z.object({
    body: zInterviewGuideGenerationRequest,
    path: z.object({
        project_id: z.string().nullable(),
        lang: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGenerateGuideResponse = zInterviewGuideOutput;

export const zGenerateGuideSectionData = z.object({
    body: zQuestionSectionGenerationRequest,
    path: z.object({
        project_id: z.string().nullable(),
        lang: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGenerateGuideSectionResponse = zQuestionSection;

export const zGenerateSectionQuestionData = z.object({
    body: zQuestionGenerationRequest,
    path: z.object({
        project_id: z.string().nullable(),
        lang: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGenerateSectionQuestionResponse = zQuestionOutput;

export const zUploadImageData = z.object({
    body: zBodyUploadImage,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetInterviewAgentsData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        lang: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetInterviewAgentsResponse = zAgentConfigsOutput;

export const zCreateInterviewAgentsData = z.object({
    body: zAgentConfigsInput,
    path: z.object({
        project_id: z.string().nullable(),
        lang: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zPreviewProbingPromptsData = z.object({
    body: zProbingAgentConfig,
    path: z.object({
        project_id: z.string().nullable(),
        lang: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zPreviewProbingPromptsResponse = zProbingPromptPreview;

export const zGetInterviewConfigData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zGetInterviewConfigResponse = zInterviewConfig;

export const zCreateInterviewConfigData = z.object({
    body: zInterviewConfig,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetInterviewModelsData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Response Get Interview Models
 *
 * Successful Response
 */
export const zGetInterviewModelsResponse = z.array(z.string());

export const zUpdateExternalParamsData = z.object({
    body: zExternalParamsRequest,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetPromptDefaultsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zGetPromptDefaultsResponse = zProbingPromptSlots;

export const zGetConsentData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string(),
        language: z.string().length(2)
    }),
    query: z.never().optional()
});

/**
 * Response Get Consent
 *
 * Successful Response
 */
export const zGetConsentResponse = zConsent.nullable();

export const zCreateConsentData = z.object({
    body: zConsent,
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetWelcomeData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string(),
        language: z.string().length(2)
    }),
    query: z.never().optional()
});

/**
 * Response Get Welcome
 *
 * Successful Response
 */
export const zGetWelcomeResponse = zWelcome.nullable();

export const zCreateWelcomeData = z.object({
    body: zBodyCreateWelcome,
    path: z.object({
        project_id: z.string().nullable(),
        language: z.string().length(2)
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zDeleteInterviewsData = z.object({
    body: zDeleteInterviewRequest,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetInterviewsData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        interview_types: z.array(zInterviewType).nullish(),
        created_at: z.iso.datetime().nullish(),
        completed: z.boolean().nullish(),
        folder_id: z.string().nullish(),
        offset: z.int().lte(100).optional().default(0),
        limit: z.int().lte(100).optional().default(20),
        column: z.string().optional().default('created_at'),
        order: z.enum(['asc', 'desc']).optional()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetInterviewsResponse = zPaginatedResponseInterviewSummaryPublic;

export const zGetMessageData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        interview_id: z.string(),
        message_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetInterviewMessagesData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        interview_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Get Interview Messages
 *
 * Successful Response
 */
export const zGetInterviewMessagesResponse = z.array(zMessagePublic);

export const zGetInterviewAudioData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        interview_id: z.string(),
        filename: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zExportMessagesData = z.object({
    body: zExportMessagesRequest,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGenerateProjectQrData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zCheckProjectOwnerData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Response Check Project Owner
 *
 * Successful Response
 */
export const zCheckProjectOwnerResponse = z.boolean();

export const zGetBackgroundInfoData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        test_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetBackgroundInfoResponse = zBackgroundInfoOptionsOutput;

export const zUpdateBackgroundInfoData = z.object({
    body: zUpdateBackgroundInfoRequest,
    path: z.object({
        project_id: z.string().nullable(),
        test_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetFixedPersonasData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        test_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Get Fixed Personas
 *
 * Successful Response
 */
export const zGetFixedPersonasResponse = z.array(z.string()).nullable();

export const zUpdateFixedPersonasData = z.object({
    body: zUpdateFixedPersonasRequest,
    path: z.object({
        project_id: z.string().nullable(),
        test_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetFixedAnswersData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        test_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zUpdateFixedAnswersData = z.object({
    body: zUpdateFixedAnswersRequest,
    path: z.object({
        project_id: z.string().nullable(),
        test_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetTestSetupsData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Response Get Test Setups
 *
 * Successful Response
 */
export const zGetTestSetupsResponse = z.array(zTestSetupPublic);

export const zCreateTestSetupData = z.object({
    body: zTestSetupCreate,
    path: z.object({
        project_id: z.string().nullable()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zCreateTestSetupResponse = zTestSetupPublic;

export const zDeleteTestSetupData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        test_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zGetIntervieweeData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string()
    }),
    query: z.object({
        interview_id: z.string()
    })
});

export const zGetTestStatusData = z.object({
    body: z.never().optional(),
    path: z.object({
        project_id: z.string().nullable(),
        test_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zRunSyntheticTestData = z.object({
    body: zSynthesizeRequest,
    path: z.object({
        project_id: z.string().nullable(),
        test_id: z.string()
    }),
    query: z.object({
        folder_id: z.string().nullish()
    }).optional()
});

export const zCreateInterviewData = z.object({
    body: zCreateInterviewRequest,
    path: z.object({
        project_id: z.string(),
        lang: zLanguageCode
    }),
    query: z.never().optional(),
    headers: z.object({
        'user-agent': z.string().nullish(),
        'X-Real-IP': z.string().nullish()
    }).optional()
});

/**
 * Response Create Interview
 *
 * Successful Response
 */
export const zCreateInterviewResponse = z.string();

export const zPutFeedbackData = z.object({
    body: zMessageFeedbackResponse,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zPutFeedbackResponse = zMessageFeedbackResponse;

export const zUploadInterviewImageData = z.object({
    body: zBodyUploadInterviewImage,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUploadInterviewImageResponse = zMediaUploadResponse;

export const zUploadAudioData = z.object({
    body: zBodyUploadAudio,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUploadAudioResponse = zMediaUploadResponse;

export const zSynthesizeSpeechData = z.object({
    body: zSpeechRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zSynthesizeSpeechResponse = z.string();

export const zLoginData2 = z.object({
    body: zLoginData,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zVerifyLoginCodeData = z.object({
    body: zVerifyLoginCodeRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zDeleteMeData = z.object({
    body: zDeleteAccountRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zMeData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zMeResponse = zUserPublic;

export const zUpdateMeData = z.object({
    body: zUserSelfUpdate,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUpdateMeResponse = zUserPublic;

export const zUpdateMyEmailData = z.object({
    body: zUpdateEmailRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUpdateMyEmailResponse = zUserPublic;

export const zUpdateMyPasswordData = z.object({
    body: zUpdatePasswordRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zRegisterData = z.object({
    body: zUserCreateRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zVerifyEmailData = z.object({
    body: zVerifyEmailRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zResendVerificationData = z.object({
    body: zResendVerificationRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zRequestAccessData = z.object({
    body: zAccessRequestCreate,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zLogoutData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zLogoutEverywhereData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zExitData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zRefreshData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zGetAccessRequestsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zProcessAccessRequestsData = z.object({
    body: zAccessRequestsProcessRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zDeleteAccessRequestsData = z.object({
    body: zAccessRequestsDeleteRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zGetInvitationsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Get Invitations
 *
 * Successful Response
 */
export const zGetInvitationsResponse = z.array(zInvitationPublic);

export const zCreateInvitationData = z.object({
    body: zInvitationCreate,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zUpdateInvitationData = z.object({
    body: zInvitationUpdate,
    path: z.object({
        invitation_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUpdateInvitationResponse = zInvitationPublic;

export const zDeleteInvitationsData = z.object({
    body: zInvitationsDeleteRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zProxyToEc2ManagerDeleteData = z.object({
    body: z.never().optional(),
    path: z.object({
        full_path: z.string()
    }),
    query: z.never().optional()
});

export const zProxyToEc2ManagerGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        full_path: z.string()
    }),
    query: z.never().optional()
});

export const zProxyToEc2ManagerPatchData = z.object({
    body: z.never().optional(),
    path: z.object({
        full_path: z.string()
    }),
    query: z.never().optional()
});

export const zProxyToEc2ManagerPostData = z.object({
    body: z.never().optional(),
    path: z.object({
        full_path: z.string()
    }),
    query: z.never().optional()
});

export const zProxyToEc2ManagerPutData = z.object({
    body: z.never().optional(),
    path: z.object({
        full_path: z.string()
    }),
    query: z.never().optional()
});

export const zDeleteUserData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        user_id: z.string()
    })
});

export const zGetUsersData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Get Users
 *
 * Successful Response
 */
export const zGetUsersResponse = z.array(zUserAdmin);

export const zUpdateAdminNoteData = z.object({
    body: zAdminNoteUpdate,
    path: z.object({
        user_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUpdateAdminNoteResponse = zUserAdmin;

export const zUpdateUserData = z.object({
    body: zUserAdminUpdate,
    path: z.object({
        user_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUpdateUserResponse = zUserAdmin;

export const zGetModelsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zGetLanguagesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Get Languages
 *
 * Successful Response
 */
export const zGetLanguagesResponse = z.array(zLanguageDict);

export const zNewsletterUnsubscribeData = z.object({
    body: zNewsletterRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zNewsletterSubscribeData = z.object({
    body: zNewsletterRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zHealthData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zVersionData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Version
 *
 * Successful Response
 */
export const zVersionResponse = zPlatformManifest.nullable();

export const zPlatformVersionData = z.object({
    body: z.never().optional(),
    path: z.object({
        platform_version: z.string()
    }),
    query: z.never().optional()
});

export const zReleasesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        limit: z.int().optional().default(10)
    }).optional()
});

/**
 * Response Releases
 *
 * Successful Response
 */
export const zReleasesResponse = z.array(zPlatformRelease);
