// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AccessRequestCreate
 */
export const zAccessRequestCreate = z.object({
    name: z.string(),
    email: z.email(),
    organization: z.string().nullish(),
    message: z.string().nullish()
});

/**
 * AccessRequestsDeleteRequest
 */
export const zAccessRequestsDeleteRequest = z.object({
    ids: z.array(z.string())
});

/**
 * AdminNoteUpdate
 */
export const zAdminNoteUpdate = z.object({
    note: z.string().nullish()
});

/**
 * AgentConfig
 */
export const zAgentConfig = z.object({
    model: z.string().optional().default('openrouter:openai/gpt-oss-120b'),
    temperature: z.number().gte(0).lte(2).optional().default(0.7),
    include: z.boolean().optional().default(true)
});

/**
 * AnnotationType
 */
export const zAnnotationType = z.enum(['tag', 'score']);

/**
 * AnalysisCategoryCreate
 */
export const zAnalysisCategoryCreate = z.object({
    project_id: z.string(),
    name: z.string(),
    description: z.string().nullish(),
    type: zAnnotationType,
    color: z.string(),
    min_value: z.int().nullish(),
    max_value: z.int().nullish()
});

/**
 * AnalysisCategoryPublic
 */
export const zAnalysisCategoryPublic = z.object({
    project_id: z.string(),
    name: z.string(),
    description: z.string().nullish(),
    type: zAnnotationType,
    color: z.string(),
    min_value: z.int().nullish(),
    max_value: z.int().nullish(),
    id: z.string(),
    created_at: z.iso.datetime()
});

/**
 * AnnotationValueCreate
 */
export const zAnnotationValueCreate = z.object({
    category_id: z.string(),
    value_int: z.int()
});

/**
 * AnnotationValuePublic
 */
export const zAnnotationValuePublic = z.object({
    category_id: z.string(),
    value_int: z.int(),
    id: z.string()
});

/**
 * AnswerLength
 */
export const zAnswerLength = z.enum([
    'short',
    'medium',
    'long'
]);

/**
 * Body_create_welcome
 */
export const zBodyCreateWelcome = z.object({
    title: z.string(),
    text: z.string(),
    email: z.email(),
    video: z.string().nullish()
});

/**
 * Body_upload_audio
 */
export const zBodyUploadAudio = z.object({
    project_id: z.string(),
    interview_id: z.string(),
    file: z.string()
});

/**
 * Body_upload_image
 */
export const zBodyUploadImage = z.object({
    primer: z.string(),
    description: z.string(),
    alt: z.string(),
    file: z.string()
});

/**
 * Body_upload_interview_image
 */
export const zBodyUploadInterviewImage = z.object({
    project_id: z.string(),
    interview_id: z.string(),
    file: z.string()
});

/**
 * Body_upload_participant_email_attachments
 */
export const zBodyUploadParticipantEmailAttachments = z.object({
    files: z.array(z.string())
});

/**
 * Body_upload_participant_reminder_email_attachments
 */
export const zBodyUploadParticipantReminderEmailAttachments = z.object({
    files: z.array(z.string())
});

/**
 * Body_upload_participants
 */
export const zBodyUploadParticipants = z.object({
    file: z.string()
});

/**
 * CheckboxItem
 */
export const zCheckboxItem = z.object({
    type: z.literal('checkbox').optional().default('checkbox'),
    required: z.boolean().optional().default(true),
    options: z.array(z.string()),
    with_other: z.boolean().optional().default(false)
});

/**
 * CollaboratorRole
 */
export const zCollaboratorRole = z.enum([
    'viewer',
    'annotator',
    'editor',
    'admin'
]);

/**
 * Collaborator
 */
export const zCollaborator = z.object({
    email: z.email(),
    role: zCollaboratorRole
});

/**
 * CollaboratorCreate
 */
export const zCollaboratorCreate = z.object({
    role: zCollaboratorRole,
    email: z.email()
});

/**
 * CommunicationTrait
 */
export const zCommunicationTrait = z.object({
    length: zAnswerLength,
    style: z.string(),
    tone: z.string()
});

/**
 * CommunicationTraits
 */
export const zCommunicationTraits = z.object({
    length: z.array(z.union([zAnswerLength, z.string()])),
    style: z.array(z.string()),
    tone: z.array(z.string())
});

/**
 * BackgroundInfoOptions
 *
 * Dataclass representing the possible values for the background info of the synthetic agents
 */
export const zBackgroundInfoOptionsInput = z.object({
    names_gender: z.array(z.tuple([z.string(), z.string()])),
    age_range: z.tuple([z.int(), z.int()]).optional().default([18, 80]),
    educations: z.array(z.string()),
    occupations: z.array(z.string()),
    locations: z.array(z.string()),
    personalities: z.array(z.string()),
    communication_traits: zCommunicationTraits,
    extra_traits: z.union([
        z.array(z.record(z.string(), z.string())),
        z.array(z.string())
    ]).nullish(),
    refusal_rate: z.tuple([z.number(), z.number()]).nullish()
});

/**
 * BackgroundInfoOptions
 *
 * Dataclass representing the possible values for the background info of the synthetic agents
 */
export const zBackgroundInfoOptionsOutput = z.object({
    names_gender: z.array(z.tuple([z.string(), z.string()])),
    age_range: z.tuple([z.int(), z.int()]).optional().default([18, 80]),
    educations: z.array(z.string()),
    occupations: z.array(z.string()),
    locations: z.array(z.string()),
    personalities: z.array(z.string()),
    communication_traits: zCommunicationTraits,
    extra_traits: z.union([
        z.array(z.record(z.string(), z.string())),
        z.array(z.string())
    ]).nullish(),
    refusal_rate: z.tuple([z.number(), z.number()]).nullish()
});

/**
 * ConditionAction
 */
export const zConditionAction = z.enum([
    'end_interview',
    'skip_section',
    'skip_question',
    'skip_probes'
]);

/**
 * ConditionEvaluation
 *
 * A single evaluation check with an optional operator to combine with the next evaluation.
 *
 * For "A AND B OR C", create:
 * [
 * ConditionEvaluation(trigger_value="A", combine_next="AND"),
 * ConditionEvaluation(trigger_value="B", combine_next="OR"),
 * ConditionEvaluation(trigger_value="C"),
 * ]
 *
 * For numeric comparisons (e.g., age >= 18):
 * ConditionEvaluation(trigger_value="18", comparison_operator=">=")
 */
export const zConditionEvaluation = z.object({
    trigger_value: z.union([
        z.string(),
        z.int(),
        z.number()
    ]),
    comparison_operator: z.enum([
        '==',
        '<',
        '<=',
        '>',
        '>='
    ]).optional().default('=='),
    combine_next: z.enum(['AND', 'OR']).nullish()
});

/**
 * ConditionTrigger
 */
export const zConditionTrigger = z.enum(['match', 'classification']);

/**
 * Consent
 */
export const zConsent = z.object({
    title: z.string(),
    text: z.string()
});

/**
 * DailyInterviewCount
 *
 * Count of interviews created per day.
 */
export const zDailyInterviewCount = z.object({
    date: z.iso.date(),
    count: z.int(),
    completed_count: z.int()
});

/**
 * DateItem
 */
export const zDateItem = z.object({
    type: z.literal('date').optional().default('date'),
    required: z.boolean().optional().default(true),
    min: z.string().nullish().default(null),
    max: z.string().nullish().default(null)
});

/**
 * DatetimeItem
 */
export const zDatetimeItem = z.object({
    type: z.literal('datetime').optional().default('datetime'),
    required: z.boolean().optional().default(true),
    min: z.string().nullish().default(null),
    max: z.string().nullish().default(null)
});

/**
 * DeleteAccountRequest
 */
export const zDeleteAccountRequest = z.object({
    password: z.string()
});

/**
 * DeleteInterviewRequest
 */
export const zDeleteInterviewRequest = z.object({
    interview_ids: z.array(z.string())
});

/**
 * DeleteParticipantsRequest
 */
export const zDeleteParticipantsRequest = z.object({
    participant_ids: z.array(z.string())
});

/**
 * DropoutPoint
 *
 * Count of dropouts at a specific question.
 */
export const zDropoutPoint = z.object({
    main_question: z.int().nullable(),
    sub_question: z.int().nullable(),
    count: z.int()
});

/**
 * ErrorResponse
 */
export const zErrorResponse = z.object({
    detail: z.string()
});

/**
 * ExperimentProjectCreate
 *
 * Input model for adding a project to an experiment.
 */
export const zExperimentProjectCreate = z.object({
    project_id: z.string(),
    weight: z.number().nullish()
});

/**
 * ExperimentCreate
 */
export const zExperimentCreate = z.object({
    title: z.string(),
    projects: z.array(zExperimentProjectCreate)
});

/**
 * ExperimentProjectPublic
 *
 * Public model for experiment-project association.
 */
export const zExperimentProjectPublic = z.object({
    id: z.string(),
    project_id: z.string(),
    weight: z.number().nullish(),
    added_at: z.iso.datetime()
});

/**
 * ExportMessagesRequest
 */
export const zExportMessagesRequest = z.object({
    interview_ids: z.array(z.string()),
    format: z.enum(['csv', 'xlsx']).optional().default('csv')
});

/**
 * ExportParticipantsRequest
 */
export const zExportParticipantsRequest = z.object({
    participant_ids: z.array(z.string()).nullish()
});

/**
 * ExternalParam
 *
 * Definition of a single external URL query parameter.
 */
export const zExternalParam = z.object({
    name: z.string().regex(/^[a-zA-Z_][a-zA-Z0-9_]*$/),
    type: z.enum([
        'str',
        'int',
        'float',
        'bool',
        'enum'
    ]),
    required: z.boolean().optional().default(true),
    default: z.union([
        z.string(),
        z.int(),
        z.number(),
        z.boolean()
    ]).nullish(),
    options: z.array(z.string()).nullish(),
    description: z.string().nullish()
});

/**
 * ExternalParamsRequest
 */
export const zExternalParamsRequest = z.object({
    params: z.array(zExternalParam)
});

/**
 * Feedback
 */
export const zFeedback = z.enum(['positive', 'negative']);

/**
 * FilteredMessagesRequest
 */
export const zFilteredMessagesRequest = z.object({
    category_ids: z.array(z.string()).nullish(),
    search_text: z.string().nullish(),
    exact_match: z.boolean().optional().default(false),
    case_sensitive: z.boolean().optional().default(false),
    questions: z.array(z.tuple([z.int(), z.int()])).nullish(),
    include_previous_on_user: z.boolean().optional().default(true)
});

/**
 * GeneratedQuestions
 */
export const zGeneratedQuestions = z.object({
    n: z.int().optional().default(0),
    max_probes_n: z.int().nullish(),
    max_probes_time: z.int().nullish()
});

/**
 * GitHashes
 */
export const zGitHashes = z.object({
    core_lib: z.string(),
    backend: z.string(),
    frontend: z.string()
});

/**
 * HistogramBucket
 *
 * A value-count pair for histogram use.
 */
export const zHistogramBucket = z.object({
    value: z.int(),
    count: z.int(),
    label: z.string()
});

/**
 * Image
 *
 * An image to show the interviewee
 */
export const zImage = z.object({
    type: z.enum([
        'audio',
        'image',
        'video'
    ]).optional().default('image'),
    name: z.string(),
    data: z.string().nullable(),
    primer: z.string().nullish().default(null),
    description: z.string(),
    alt: z.string()
});

/**
 * InterviewDurationStats
 *
 * Statistics about interview duration (time spent).
 */
export const zInterviewDurationStats = z.object({
    min_seconds: z.int(),
    max_seconds: z.int(),
    avg_seconds: z.number(),
    sum_seconds: z.number()
});

/**
 * InterviewGuideGenerationRequest
 */
export const zInterviewGuideGenerationRequest = z.object({
    prompt: z.string()
});

/**
 * InterviewMessage
 */
export const zInterviewMessage = z.object({
    message: z.string()
});

/**
 * InterviewStatus
 */
export const zInterviewStatus = z.enum([
    'active',
    'inactive',
    'completed'
]);

/**
 * InterviewStatusCount
 *
 * Count of interviews by status.
 */
export const zInterviewStatusCount = z.object({
    status: zInterviewStatus,
    count: z.int()
});

/**
 * InterviewSubject
 *
 * Dataclass representing the interview subject
 */
export const zInterviewSubject = z.object({
    name: z.string(),
    age: z.int(),
    gender: z.string(),
    education: z.string(),
    occupation: z.string(),
    location: z.string(),
    personality: z.string(),
    communication_trait: zCommunicationTrait,
    extra_traits: z.union([
        z.record(z.string(), z.string()),
        z.string()
    ]).nullish(),
    refusal_rate: z.number().gte(0).lte(1).optional().default(0)
});

/**
 * InterviewTimeOfDayCount
 */
export const zInterviewTimeOfDayCount = z.object({
    time: z.string(),
    count: z.int()
});

/**
 * InterviewType
 */
export const zInterviewType = z.enum([
    'manual_test',
    'synthetic_test',
    'distributed'
]);

/**
 * IntervieweeCreate
 */
export const zIntervieweeCreate = z.object({
    interview_id: z.string(),
    interview_subject: z.union([
        zInterviewSubject,
        z.string()
    ])
});

/**
 * Interviewer
 */
export const zInterviewer = z.enum(['human', 'ai']);

/**
 * InvitationsDeleteRequest
 */
export const zInvitationsDeleteRequest = z.object({
    ids: z.array(z.string())
});

export const zLanguageCode = z.string().length(2);

/**
 * Body_add_project_language
 */
export const zBodyAddProjectLanguage = z.object({
    language: zLanguageCode,
    translate: z.boolean().optional().default(true)
});

/**
 * CreateProjectRequest
 */
export const zCreateProjectRequest = z.object({
    title: z.string(),
    default_language: zLanguageCode
});

/**
 * LanguageDict
 */
export const zLanguageDict = z.object({
    name: z.string(),
    code: zLanguageCode
});

/**
 * LikertItem
 */
export const zLikertItem = z.object({
    type: z.literal('likert').optional().default('likert'),
    required: z.boolean().optional().default(true),
    options: z.array(z.string()),
    ui: z.enum(['radio', 'slider']).optional().default('radio')
});

/**
 * LoginData
 */
export const zLoginData = z.object({
    email: z.string(),
    password: z.string(),
    extended: z.boolean().optional().default(false)
});

/**
 * MediaUploadResponse
 */
export const zMediaUploadResponse = z.object({
    message: z.string(),
    filename: z.string()
});

/**
 * MessageAnnotationCreate
 */
export const zMessageAnnotationCreate = z.object({
    message_id: z.string(),
    user_id: z.string(),
    comment: z.string().nullish(),
    values: z.array(zAnnotationValueCreate)
});

/**
 * MessageAnnotationPublic
 */
export const zMessageAnnotationPublic = z.object({
    message_id: z.string(),
    user_id: z.string(),
    comment: z.string().nullish(),
    id: z.string(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    values: z.array(zAnnotationValuePublic)
});

/**
 * MessageCountStats
 *
 * Statistics about message counts per interview.
 */
export const zMessageCountStats = z.object({
    min_messages: z.int(),
    max_messages: z.int(),
    avg_messages: z.number(),
    sum_messages: z.int()
});

/**
 * MessageFeedbackResponse
 */
export const zMessageFeedbackResponse = z.object({
    interview_id: z.string(),
    project_id: z.string(),
    message_id: z.int(),
    feedback: zFeedback.nullable()
});

/**
 * MessageRole
 */
export const zMessageRole = z.enum([
    'system',
    'assistant',
    'user'
]);

/**
 * MessageType
 */
export const zMessageType = z.enum([
    'text',
    'image',
    'audio',
    'custom_token',
    'survey_item'
]);

/**
 * MonitoringStats
 *
 * Aggregated monitoring statistics for a project.
 */
export const zMonitoringStats = z.object({
    total_interviews: z.int(),
    completion_rate: z.number(),
    interviews_by_status: z.array(zInterviewStatusCount),
    interviews_over_time: z.array(zDailyInterviewCount),
    interviews_by_time_of_day: z.array(zInterviewTimeOfDayCount),
    duration_stats: zInterviewDurationStats.nullable(),
    message_count_stats: zMessageCountStats.nullable(),
    duration_histogram: z.array(zHistogramBucket),
    message_count_histogram: z.array(zHistogramBucket),
    message_length_histogram: z.array(zHistogramBucket),
    dropout_stats: z.array(zDropoutPoint)
});

/**
 * NewsletterRequest
 */
export const zNewsletterRequest = z.object({
    email: z.email()
});

/**
 * NumberItem
 */
export const zNumberItem = z.object({
    type: z.literal('number').optional().default('number'),
    required: z.boolean().optional().default(true),
    min: z.union([
        z.int(),
        z.number()
    ]).nullish().default(null),
    max: z.union([
        z.int(),
        z.number()
    ]).nullish().default(null),
    step: z.union([
        z.int(),
        z.number()
    ]).nullish().default(1)
});

/**
 * ParticipantCreate
 */
export const zParticipantCreate = z.object({
    name: z.string().nullish(),
    email: z.email().nullish(),
    pid: z.string().nullish(),
    participating: z.boolean().optional().default(true),
    lang: zLanguageCode.nullish()
});

/**
 * ParticipantEmailAttachment
 */
export const zParticipantEmailAttachment = z.object({
    filename: z.string(),
    size: z.int(),
    content_type: z.string().nullish()
});

/**
 * ParticipantEmailTemplateRequest
 */
export const zParticipantEmailTemplateRequest = z.object({
    subject: z.string().nullish(),
    template: z.string().nullish()
});

/**
 * ParticipantPublic
 */
export const zParticipantPublic = z.object({
    name: z.string().nullish(),
    email: z.email().nullish(),
    pid: z.string(),
    participating: z.boolean().optional().default(true),
    lang: zLanguageCode.nullish(),
    id: z.string(),
    project_id: z.string(),
    participant_id: z.string(),
    folder_id: z.string(),
    created_at: z.iso.datetime(),
    latest_interview_at: z.iso.datetime().nullish(),
    latest_interview_status: zInterviewStatus.nullish()
});

/**
 * PlatformManifest
 */
export const zPlatformManifest = z.object({
    platform_version: z.string(),
    core_lib: z.string(),
    backend: z.string(),
    frontend: z.string(),
    build_time: z.iso.datetime(),
    git: zGitHashes
});

/**
 * ProbingContext
 */
export const zProbingContext = z.enum(['section', 'question']);

/**
 * ProbingPromptPreview
 *
 * Rendered probing-agent prompts with the project's editable slots injected.
 *
 * Interview-time context (transcript, framing, etc.) is shown as labelled
 * placeholders since those values only exist while an interview is running.
 */
export const zProbingPromptPreview = z.object({
    system: z.string(),
    instruction: z.string()
});

/**
 * ProbingPromptSlots
 *
 * User-editable regions of the probing agent's system and instruction prompts.
 *
 * Each field is an override: when left as ``None`` the corresponding default
 * from ``DEFAULT_PROBING_SLOTS`` is used at render time, so improvements to the
 * defaults flow through to projects that have not customized that slot.
 */
export const zProbingPromptSlots = z.object({
    persona: z.string().nullish(),
    question_qualities: z.array(z.string()).nullish(),
    guidelines: z.array(z.string()).nullish(),
    instructions: z.array(z.string()).nullish()
});

/**
 * ProbingAgentConfig
 */
export const zProbingAgentConfig = z.object({
    model: z.string().optional().default('openrouter:openai/gpt-oss-120b'),
    temperature: z.number().gte(0).lte(2).optional().default(0.7),
    include: z.boolean().optional().default(true),
    few_shot_examples: z.array(z.string()).nullish(),
    prompt_slots: zProbingPromptSlots.optional()
});

/**
 * ProbingStrategy
 */
export const zProbingStrategy = z.enum([
    'standard',
    'dice_master_to_one_probe',
    'dice_ensemble_to_master_probe',
    'dice_master_to_ensemble_to_one_probe'
]);

/**
 * InterviewConfig
 */
export const zInterviewConfig = z.object({
    default_language: zLanguageCode.optional().default('EN'),
    with_consent: z.boolean().optional().default(true),
    with_welcome: z.boolean().optional().default(true),
    with_audio: z.boolean().optional().default(false),
    probing_strategy: z.array(zProbingStrategy).optional()
});

/**
 * InterviewConfigWithModels
 */
export const zInterviewConfigWithModels = z.object({
    default_language: zLanguageCode.optional().default('EN'),
    with_consent: z.boolean().optional().default(true),
    with_welcome: z.boolean().optional().default(true),
    with_audio: z.boolean().optional().default(false),
    probing_strategy: z.array(zProbingStrategy).optional(),
    models: z.array(z.string())
});

/**
 * ProjectFolderCreate
 */
export const zProjectFolderCreate = z.object({
    title: z.string(),
    folder_collaborations: z.array(zCollaborator).optional().default([])
});

/**
 * ProjectFolderEdit
 */
export const zProjectFolderEdit = z.object({
    title: z.string()
});

/**
 * ProjectStatus
 */
export const zProjectStatus = z.enum(['active', 'inactive']);

/**
 * ExperimentPublic
 */
export const zExperimentPublic = z.object({
    id: z.string(),
    title: z.string(),
    user_id: z.string(),
    created_at: z.iso.datetime(),
    status: zProjectStatus.optional().default('active'),
    projects: z.array(zExperimentProjectPublic).optional().default([])
});

/**
 * ProjectStatusChangeRequest
 */
export const zProjectStatusChangeRequest = z.object({
    status: zProjectStatus
});

/**
 * ProjectTitleUpdateRequest
 */
export const zProjectTitleUpdateRequest = z.object({
    title: z.string()
});

/**
 * QuestionBase
 *
 * A question that can be asked to the interviewee
 */
export const zQuestionBase = z.object({
    description: z.string().nullish(),
    main_question: z.string(),
    probes: z.array(z.string()).nullish(),
    max_probes_n: z.int().gte(0).nullish().default(3),
    max_probes_time: z.number().gt(0).nullish()
});

/**
 * QuestionContext
 *
 * The index of a question in a section
 * section [int]: The index of the section
 * question [int]: The index of the question
 * part
 */
export const zQuestionContext = z.object({
    section: z.int(),
    question: z.int(),
    part: z.enum([
        'main',
        'probes',
        'both'
    ]).optional().default('main')
});

/**
 * Condition
 *
 * Create a condition that must be met to ask a question
 */
export const zCondition = z.object({
    question_context: zQuestionContext,
    evaluation: z.array(zConditionEvaluation),
    negated: z.boolean().optional().default(false),
    trigger_type: zConditionTrigger.optional().default('match'),
    combine_next: z.enum(['AND', 'OR']).nullish()
});

/**
 * Conditions
 */
export const zConditionsInput = z.object({
    conditions: z.array(zCondition),
    action: zConditionAction
});

/**
 * Conditions
 */
export const zConditionsOutput = z.object({
    conditions: z.array(zCondition),
    action: zConditionAction
});

/**
 * QuestionGenerationRequest
 */
export const zQuestionGenerationRequest = z.object({
    prompt: z.string(),
    section_idx: z.int(),
    max_probes_n: z.int().nullish(),
    max_probes_time: z.int().nullish()
});

export const zQuestionIndex = z.tuple([z.int(), z.int()]);

/**
 * QuestionSection
 *
 * A section of questions that all revolve around the same topic
 */
export const zQuestionSection = z.object({
    description: z.string(),
    questions: z.array(zQuestionBase),
    shuffle: z.boolean().optional().default(false),
    ai_generated_questions: zGeneratedQuestions.optional().default({ n: 0 })
});

/**
 * QuestionSectionGenerationRequest
 */
export const zQuestionSectionGenerationRequest = z.object({
    prompt: z.string()
});

/**
 * RadioItem
 */
export const zRadioItem = z.object({
    type: z.literal('radio').optional().default('radio'),
    required: z.boolean().optional().default(true),
    options: z.array(z.string()),
    with_other: z.boolean().optional().default(false)
});

/**
 * Reference
 *
 * Create a reference to a previous answer, useful when refering back to a
 * previous answer, eg. an answer to a survey item. If used, the main question
 * must contains an empty `{}` as a placeholder for the referred answer.
 */
export const zReference = z.object({
    question_index: zQuestionIndex
});

/**
 * ResendVerificationRequest
 */
export const zResendVerificationRequest = z.object({
    email: z.email()
});

/**
 * Scope
 */
export const zScope = z.enum([
    'admin',
    'user',
    'demo',
    'guest'
]);

/**
 * AccessRequestsProcessRequest
 */
export const zAccessRequestsProcessRequest = z.object({
    ids: z.array(z.string()),
    scopes: z.array(zScope),
    action: z.enum(['approve', 'deny'])
});

/**
 * SecurityConfig
 */
export const zSecurityConfig = z.object({
    model: z.string().optional().default('openrouter:openai/gpt-oss-120b'),
    temperature: z.number().gte(0).lte(2).optional().default(0.7),
    include: z.boolean().optional().default(false),
    sensitive_subjects: z.array(z.unknown()).nullish()
});

/**
 * SendParticipantEmailRequest
 */
export const zSendParticipantEmailRequest = z.object({
    participant_ids: z.array(z.string()).nullish()
});

/**
 * SendParticipantEmailResponse
 */
export const zSendParticipantEmailResponse = z.object({
    sent: z.array(z.string()),
    skipped: z.array(z.string())
});

/**
 * SliderItem
 */
export const zSliderItem = z.object({
    type: z.literal('slider').optional().default('slider'),
    required: z.boolean().optional().default(true),
    min: z.union([
        z.int(),
        z.number()
    ]),
    max: z.union([
        z.int(),
        z.number()
    ]),
    min_label: z.string().nullish().default(null),
    max_label: z.string().nullish().default(null),
    step: z.union([
        z.int(),
        z.number()
    ]).nullish().default(1)
});

/**
 * SpeechRequest
 */
export const zSpeechRequest = z.object({
    message_id: z.int()
});

/**
 * SynthesizeRequest
 */
export const zSynthesizeRequest = z.object({
    answering_model: z.string().nullish(),
    n_interviews: z.int().gte(1).lte(100),
    language: zLanguageCode.optional().default('EN'),
    delay_before_answers: z.tuple([z.number(), z.number()]).nullish()
});

/**
 * TestType
 */
export const zTestType = z.enum([
    'shuffled_ai',
    'fixed_ai',
    'fixed_answers'
]);

/**
 * CreateInterviewRequest
 */
export const zCreateInterviewRequest = z.object({
    interviewer: zInterviewer.optional().default('ai'),
    interview_type: zInterviewType.optional().default('distributed'),
    test_run_id: z.string().nullish(),
    experiment_id: z.string().nullish(),
    synthetic_test_type: zTestType.nullish(),
    participant_id: z.string().nullish(),
    pid: z.string().nullish(),
    external_params: z.record(z.string(), z.unknown()).nullish(),
    referer: z.string().nullish()
});

/**
 * TestSetupCreate
 */
export const zTestSetupCreate = z.object({
    name: z.string().nullish(),
    type: zTestType,
    project_id: z.string(),
    answering_model: z.string().optional().default('openrouter:openai/gpt-oss-120b'),
    last_updated: z.iso.datetime().nullish(),
    language: zLanguageCode.optional().default('EN'),
    n_interviews: z.int().optional().default(5),
    delay_before_answers: z.tuple([z.number(), z.number()]).nullish()
});

/**
 * TestSetupPublic
 */
export const zTestSetupPublic = z.object({
    name: z.string().nullish(),
    type: zTestType,
    project_id: z.string(),
    answering_model: z.string().optional().default('openrouter:openai/gpt-oss-120b'),
    last_updated: z.iso.datetime().nullish(),
    language: zLanguageCode.optional().default('EN'),
    n_interviews: z.int().optional().default(5),
    delay_before_answers: z.tuple([z.number(), z.number()]).nullish(),
    n_runs: z.int(),
    id: z.string(),
    created_at: z.iso.datetime(),
    background_info: zBackgroundInfoOptionsOutput.nullish(),
    fixed_answers: z.array(z.string()).nullish(),
    fixed_personas: z.array(z.string()).nullish()
});

/**
 * TimeDelta
 */
export const zTimeDelta = z.object({
    days: z.int().optional().default(0),
    seconds: z.int().optional().default(0),
    microseconds: z.int().optional().default(0),
    milliseconds: z.int().optional().default(0),
    minutes: z.int().optional().default(0),
    hours: z.int().optional().default(0),
    weeks: z.int().optional().default(0)
});

/**
 * InvitationCreate
 */
export const zInvitationCreate = z.object({
    expires_at: z.iso.datetime().nullish(),
    reuseable: z.boolean().optional().default(false),
    user_scope: zScope.optional().default('user'),
    user_expires: z.union([
        z.iso.datetime(),
        zTimeDelta
    ]).nullish(),
    title: z.string().nullish(),
    access_request_id: z.string().nullish()
});

/**
 * InvitationPublic
 */
export const zInvitationPublic = z.object({
    expires_at: z.iso.datetime().nullish(),
    reuseable: z.boolean().optional().default(false),
    user_scope: zScope.optional().default('user'),
    user_expires: z.union([
        z.iso.datetime(),
        zTimeDelta
    ]).nullish(),
    title: z.string().nullish(),
    access_request_id: z.string().nullish(),
    id: z.string(),
    email: z.string().nullable(),
    invitation_link: z.string().readonly()
});

/**
 * TimeItem
 */
export const zTimeItem = z.object({
    type: z.literal('time').optional().default('time'),
    required: z.boolean().optional().default(true),
    min: z.string().nullish().default(null),
    max: z.string().nullish().default(null)
});

/**
 * MessagePublic
 */
export const zMessagePublic = z.object({
    message_id: z.int(),
    content: z.string(),
    role: zMessageRole,
    interview_id: z.string(),
    project_id: z.string(),
    message_type: zMessageType.optional().default('text'),
    section: z.int().nullish(),
    main_question: z.int().nullish(),
    sub_question: z.int().nullish(),
    is_introduction: z.boolean().optional().default(false),
    outro: z.boolean().optional().default(false),
    timed: z.boolean().optional().default(false),
    can_answer: z.boolean().optional().default(true),
    include_in_history: z.boolean().optional().default(true),
    attachment: z.string().nullish(),
    audio_file: z.string().nullish(),
    feedback: zFeedback.nullish(),
    created_at: z.iso.datetime(),
    image: z.union([
        zImage,
        z.array(zImage)
    ]).nullish(),
    survey_item: z.union([
        zRadioItem,
        zCheckboxItem,
        zLikertItem,
        zSliderItem,
        zNumberItem,
        zDateItem,
        zDatetimeItem,
        zTimeItem
    ]).nullish(),
    skipped_by_condition: z.boolean().optional().default(false),
    id: z.string(),
    annotations: z.array(zMessageAnnotationPublic).optional().default([]),
    interview_type: zInterviewType
});

/**
 * InterviewSummaryPublic
 */
export const zInterviewSummaryPublic = z.object({
    id: z.string(),
    language: zLanguageCode.optional().default('EN'),
    interviewer: zInterviewer.optional().default('ai'),
    status: zInterviewStatus,
    type: zInterviewType,
    created_at: z.iso.datetime(),
    last_updated: z.iso.datetime().nullish(),
    total_time_spent: z.int().optional().default(0),
    n_messages: z.int(),
    messages: z.array(zMessagePublic),
    test_name: z.string().nullish()
});

/**
 * PaginatedResponse[InterviewSummaryPublic]
 */
export const zPaginatedResponseInterviewSummaryPublic = z.object({
    total: z.int(),
    items: z.array(zInterviewSummaryPublic)
});

/**
 * Question
 *
 * A question that can be asked to the interviewee
 */
export const zQuestionInput = z.object({
    description: z.string().nullish(),
    main_question: z.string(),
    probes: z.array(z.string()).nullish(),
    max_probes_n: z.int().gte(0).nullish().default(3),
    max_probes_time: z.number().gt(0).nullish(),
    survey_item: z.union([
        zRadioItem,
        zCheckboxItem,
        zLikertItem,
        zSliderItem,
        zNumberItem,
        zDateItem,
        zDatetimeItem,
        zTimeItem
    ]).nullish(),
    can_answer: z.boolean().optional().default(true),
    alternative_main_questions: z.array(z.string()).nullish(),
    check_if_answered: z.boolean().optional().default(false),
    check_if_exhausted: z.boolean().optional().default(false),
    can_skip: z.boolean().optional().default(true),
    shuffle: z.boolean().optional().default(false),
    create_segue: z.boolean().optional().default(false),
    exclude_from_history: z.boolean().optional().default(false),
    references: z.array(zReference).nullish(),
    image: zImage.nullish(),
    user_image: z.boolean().optional().default(false),
    conditions: zConditionsInput.nullish(),
    probing_context: zProbingContext.nullish(),
    index: zQuestionIndex.nullish()
});

/**
 * Question
 *
 * A question that can be asked to the interviewee
 */
export const zQuestionOutput = z.object({
    description: z.string().nullish(),
    main_question: z.string(),
    probes: z.array(z.string()).nullish(),
    max_probes_n: z.int().gte(0).nullish().default(3),
    max_probes_time: z.number().gt(0).nullish(),
    survey_item: z.union([
        zRadioItem,
        zCheckboxItem,
        zLikertItem,
        zSliderItem,
        zNumberItem,
        zDateItem,
        zDatetimeItem,
        zTimeItem
    ]).nullish(),
    can_answer: z.boolean().optional().default(true),
    alternative_main_questions: z.array(z.string()).nullish(),
    check_if_answered: z.boolean().optional().default(false),
    check_if_exhausted: z.boolean().optional().default(false),
    can_skip: z.boolean().optional().default(true),
    shuffle: z.boolean().optional().default(false),
    create_segue: z.boolean().optional().default(false),
    exclude_from_history: z.boolean().optional().default(false),
    references: z.array(zReference).nullish(),
    image: zImage.nullish(),
    user_image: z.boolean().optional().default(false),
    conditions: zConditionsOutput.nullish(),
    probing_context: zProbingContext.nullish(),
    index: zQuestionIndex.nullish()
});

/**
 * QuestionSection[Question]
 */
export const zQuestionSectionQuestionInput = z.object({
    description: z.string(),
    questions: z.array(zQuestionInput),
    shuffle: z.boolean().optional().default(false),
    ai_generated_questions: zGeneratedQuestions.optional().default({ n: 0 })
});

/**
 * QuestionSection[Question]
 */
export const zQuestionSectionQuestionOutput = z.object({
    description: z.string(),
    questions: z.array(zQuestionOutput),
    shuffle: z.boolean().optional().default(false),
    ai_generated_questions: zGeneratedQuestions.optional().default({ n: 0 })
});

/**
 * TimedMessage
 *
 * A message that is displayed to the interviewee after a certain amount of time
 */
export const zTimedMessage = z.object({
    message: z.string(),
    time: z.int(),
    include_in_history: z.boolean().optional().default(false),
    as_modal: z.boolean().optional().default(false)
});

/**
 * InterviewGuide
 */
export const zInterviewGuideInput = z.object({
    framing: z.string().optional().default(''),
    introduction: z.string().optional().default(''),
    question_sections: z.array(zQuestionSectionQuestionInput).optional(),
    outro: z.string().nullish(),
    extra_variables: z.array(z.string()).optional(),
    timed_messages: z.array(zTimedMessage).nullish(),
    ai_generated_sections: z.int().optional().default(0)
});

/**
 * AssistanceChatRequest
 */
export const zAssistanceChatRequest = z.object({
    prompt: z.string(),
    guide: zInterviewGuideInput
});

/**
 * InterviewGuide
 */
export const zInterviewGuideOutput = z.object({
    framing: z.string().optional().default(''),
    introduction: z.string().optional().default(''),
    question_sections: z.array(zQuestionSectionQuestionOutput).optional(),
    outro: z.string().nullish(),
    extra_variables: z.array(z.string()).optional(),
    timed_messages: z.array(zTimedMessage).nullish(),
    ai_generated_sections: z.int().optional().default(0)
});

/**
 * UpdateBackgroundInfoRequest
 */
export const zUpdateBackgroundInfoRequest = z.object({
    background_info: zBackgroundInfoOptionsInput
});

/**
 * UpdateEmailRequest
 */
export const zUpdateEmailRequest = z.object({
    password: z.string(),
    new_email: z.email()
});

/**
 * UpdateFixedAnswersRequest
 */
export const zUpdateFixedAnswersRequest = z.object({
    answers: z.array(z.string())
});

/**
 * UpdateFixedPersonasRequest
 */
export const zUpdateFixedPersonasRequest = z.object({
    fixed_personas: z.array(z.string())
});

/**
 * UpdatePasswordRequest
 */
export const zUpdatePasswordRequest = z.object({
    current_password: z.string(),
    new_password: z.string().min(8)
});

/**
 * UserAdmin
 */
export const zUserAdmin = z.object({
    email: z.email(),
    first_name: z.string(),
    last_name: z.string().nullish(),
    created_at: z.iso.datetime(),
    last_active: z.iso.datetime(),
    last_login: z.iso.datetime(),
    scope: zScope.optional().default('user'),
    id: z.string(),
    invitation_title: z.string().nullish(),
    expires_at: z.iso.datetime().nullish(),
    with_demo_features: z.boolean(),
    organization: z.string().nullish(),
    access_request_message: z.string().nullish(),
    admin_note: z.string().nullish(),
    admin_note_updated_at: z.iso.datetime().nullish(),
    two_factor_enabled: z.boolean().optional().default(true)
});

/**
 * UserCreateRequest
 *
 * API request model for user registration.
 */
export const zUserCreateRequest = z.object({
    email: z.email(),
    first_name: z.string(),
    last_name: z.string().nullish(),
    created_at: z.iso.datetime().optional(),
    last_active: z.iso.datetime().optional(),
    last_login: z.iso.datetime().optional(),
    scope: zScope.optional().default('user'),
    invite_token: z.union([
        z.string(),
        z.string()
    ]).nullable(),
    research_consent: z.boolean().optional().default(false),
    password: z.string().min(8)
});

/**
 * UserPublic
 */
export const zUserPublic = z.object({
    email: z.email(),
    first_name: z.string(),
    last_name: z.string().nullish(),
    created_at: z.iso.datetime(),
    last_active: z.iso.datetime(),
    last_login: z.iso.datetime(),
    scope: zScope.optional().default('user'),
    id: z.string(),
    invitation_title: z.string().nullish(),
    expires_at: z.iso.datetime().nullish(),
    with_demo_features: z.boolean(),
    organization: z.string().nullish()
});

/**
 * CollaboratorPublic
 */
export const zCollaboratorPublic = z.object({
    role: zCollaboratorRole,
    id: z.string(),
    user: zUserPublic,
    added_at: z.iso.datetime()
});

/**
 * ProjectFolderPublic
 */
export const zProjectFolderPublic = z.object({
    title: z.string(),
    id: z.string(),
    collaborators: z.array(zCollaboratorPublic).optional().default([])
});

/**
 * ProjectPublic
 */
export const zProjectPublic = z.object({
    id: z.string(),
    title: z.string(),
    created_at: z.iso.datetime(),
    last_updated: z.iso.datetime().nullish(),
    status: zProjectStatus.optional().default('active'),
    config: zInterviewConfig,
    external_params: z.array(zExternalParam).nullish(),
    owner_id: z.string(),
    n_interviews: z.int().nullish(),
    available_languages: z.array(zLanguageDict).nullish(),
    tests: z.array(zTestSetupPublic).nullish(),
    owner: zUserPublic
});

/**
 * ProjectFolderWithProjects
 */
export const zProjectFolderWithProjects = z.object({
    title: z.string(),
    id: z.string(),
    collaborators: z.array(zCollaboratorPublic).optional().default([]),
    projects: z.array(zProjectPublic)
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * VerifyEmailRequest
 */
export const zVerifyEmailRequest = z.object({
    token: z.string()
});

/**
 * VerifyLoginCodeRequest
 */
export const zVerifyLoginCodeRequest = z.object({
    email: z.string(),
    code: z.string(),
    extended: z.boolean().optional().default(false)
});

/**
 * VisualConfig
 */
export const zVisualConfig = z.object({
    model: z.string().optional().default('llava'),
    temperature: z.number().gte(0).lte(2).optional().default(0.7),
    include: z.boolean().optional().default(false)
});

/**
 * AgentConfigs
 */
export const zAgentConfigsInput = z.object({
    probing: zProbingAgentConfig.optional(),
    classification: zAgentConfig.optional(),
    guide: zAgentConfig.optional(),
    history: zAgentConfig.optional(),
    security: zSecurityConfig.optional(),
    visual: zVisualConfig.optional(),
    answering: zAgentConfig.optional(),
    reformulation: zAgentConfig.optional()
});

/**
 * AgentConfigs
 */
export const zAgentConfigsOutput = z.object({
    probing: zProbingAgentConfig.optional(),
    classification: zAgentConfig.optional(),
    guide: zAgentConfig.optional(),
    history: zAgentConfig.optional(),
    security: zSecurityConfig.optional(),
    visual: zVisualConfig.optional(),
    answering: zAgentConfig.optional(),
    reformulation: zAgentConfig.optional()
});

/**
 * Welcome
 */
export const zWelcome = z.object({
    title: z.string(),
    text: z.string(),
    email: z.email(),
    video_file_name: z.string().nullish(),
    with_id: z.boolean().optional().default(true)
});

/**
 * _Unset
 */
export const zUnset = z.enum(['UNSET']);

/**
 * InvitationUpdate
 */
export const zInvitationUpdate = z.object({
    email: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET'),
    expires_at: z.union([
        z.iso.datetime(),
        zUnset
    ]).nullish().default('UNSET'),
    reuseable: z.union([
        z.boolean(),
        zUnset
    ]).optional().default('UNSET'),
    user_scope: z.union([
        zScope,
        zUnset
    ]).optional().default('UNSET'),
    user_expires: z.union([
        z.iso.datetime(),
        zTimeDelta,
        zUnset
    ]).nullish().default('UNSET'),
    title: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET')
});

/**
 * ParticipantUpdate
 */
export const zParticipantUpdate = z.object({
    name: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET'),
    email: z.union([
        z.email(),
        zUnset
    ]).nullish().default('UNSET'),
    pid: z.union([
        z.string(),
        zUnset
    ]).optional().default('UNSET'),
    participating: z.union([
        z.boolean(),
        zUnset
    ]).optional().default('UNSET')
});

/**
 * UserAdminUpdate
 */
export const zUserAdminUpdate = z.object({
    scope: z.union([
        zScope,
        zUnset
    ]).optional().default('UNSET'),
    with_demo_features: z.union([
        z.boolean(),
        zUnset
    ]).optional().default('UNSET'),
    organization: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET'),
    expires_at: z.union([
        z.iso.datetime(),
        zUnset
    ]).nullish().default('UNSET'),
    two_factor_enabled: z.union([
        z.boolean(),
        zUnset
    ]).optional().default('UNSET')
});

/**
 * UserSelfUpdate
 *
 * Profile fields a user may change on their own account.
 */
export const zUserSelfUpdate = z.object({
    first_name: z.union([
        z.string(),
        zUnset
    ]).optional().default('UNSET'),
    last_name: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET'),
    organization: z.union([
        z.string(),
        zUnset
    ]).nullish().default('UNSET')
});

/**
 * AuthToken
 */
export const zAuthToken = z.object({
    user_id: z.string(),
    scope: zScope
});

/**
 * ChatMessage
 *
 * Format of messages sent to the browser.
 */
export const zChatMessage = z.object({
    type: z.enum([
        'message',
        'question',
        'section'
    ]).optional().default('message'),
    role: z.enum(['user', 'model']),
    timestamp: z.string(),
    content: z.string()
});

/**
 * CustomToken
 */
export const zCustomToken = z.enum([
    '<|endofprobe|>',
    '<|endofsection|>',
    '<|endofinterview|>',
    '<|skipquestion|>',
    '<|skipsection|>',
    '<|noanswer|>',
    '<|restartinterview|>'
]);

/**
 * InterviewRole
 */
export const zInterviewRole = z.enum(['interviewer', 'respondent']);

/**
 * InterviewToken
 */
export const zInterviewToken = z.object({
    project_id: z.string(),
    interview_id: z.string(),
    interviewer: zInterviewer,
    role: zInterviewRole.optional().default('respondent')
});

/**
 * OutgoingData
 */
export const zOutgoingData = z.object({
    type: z.literal('data').optional().default('data'),
    content: z.string().nullish().default(null),
    progress: z.number().gte(0).lte(100).nullish().default(null),
    error: z.enum(['InstanceInitializing', 'InferenceError']).nullish().default(null)
});

/**
 * OutgoingHistoryMessage
 */
export const zOutgoingHistoryMessage = z.object({
    type: z.literal('history').optional().default('history'),
    content: z.string(),
    role: zMessageRole,
    message_id: z.int(),
    feedback: zFeedback.nullish().default(null),
    image: z.union([
        zImage,
        z.array(zImage)
    ]).nullish().default(null),
    survey_item: z.union([
        zRadioItem,
        zCheckboxItem,
        zLikertItem,
        zSliderItem,
        zNumberItem,
        zDateItem,
        zDatetimeItem,
        zTimeItem
    ]).nullish().default(null)
});

/**
 * OutgoingMessage
 */
export const zOutgoingMessage = z.object({
    type: z.literal('message').optional().default('message'),
    content: z.string(),
    role: zMessageRole,
    message_id: z.int(),
    feedback: zFeedback.nullish().default(null),
    image: z.union([
        zImage,
        z.array(zImage)
    ]).nullish().default(null),
    survey_item: z.union([
        zRadioItem,
        zCheckboxItem,
        zLikertItem,
        zSliderItem,
        zNumberItem,
        zDateItem,
        zDatetimeItem,
        zTimeItem
    ]).nullish().default(null),
    can_answer: z.boolean().optional().default(true),
    user_image: z.boolean().optional().default(false),
    progress: z.number().gte(0).lte(100).nullish().default(null),
    is_probe: z.boolean().optional().default(false)
});

/**
 * ReceivedData
 */
export const zReceivedData = z.object({
    type: z.enum([
        'message',
        'image',
        'audio'
    ]),
    message_type: zMessageType.nullish().default(null),
    content: z.string(),
    filename: z.string().nullish().default(null)
});

/**
 * InvitationPublic
 */
export const zInvitationPublicWritable = z.object({
    expires_at: z.iso.datetime().nullish(),
    reuseable: z.boolean().optional().default(false),
    user_scope: zScope.optional().default('user'),
    user_expires: z.union([
        z.iso.datetime(),
        zTimeDelta
    ]).nullish(),
    title: z.string().nullish(),
    access_request_id: z.string().nullish(),
    id: z.string(),
    email: z.string().nullable()
});

export const zGetAnalysisCategoriesPath = z.object({
    project_id: z.string()
});

/**
 * Response Get Analysis Categories
 *
 * Successful Response
 */
export const zGetAnalysisCategoriesResponse = z.array(zAnalysisCategoryPublic);

export const zCreateAnalysisCategoryBody = zAnalysisCategoryCreate;

export const zCreateAnalysisCategoryPath = z.object({
    project_id: z.string()
});

export const zDeleteAnalysisCategoryPath = z.object({
    category_id: z.string()
});

export const zUpdateAnalysisCategoryBody = zAnalysisCategoryCreate;

export const zUpdateAnalysisCategoryPath = z.object({
    category_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateAnalysisCategoryResponse = zAnalysisCategoryPublic;

export const zGetMessageAnnotationsPath = z.object({
    message_id: z.string()
});

/**
 * Response Get Message Annotations
 *
 * Successful Response
 */
export const zGetMessageAnnotationsResponse = z.array(zMessageAnnotationPublic);

export const zAddMessageAnnotationBody = zMessageAnnotationCreate;

export const zAddMessageAnnotationPath = z.object({
    message_id: z.string()
});

/**
 * Successful Response
 */
export const zAddMessageAnnotationResponse = zMessageAnnotationPublic;

export const zDeleteMessageAnnotationPath = z.object({
    annotation_id: z.string()
});

export const zUpdateMessageAnnotationBody = zMessageAnnotationCreate;

export const zUpdateMessageAnnotationPath = z.object({
    annotation_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateMessageAnnotationResponse = zMessageAnnotationPublic;

export const zGetFilteredMessagesCountBody = zFilteredMessagesRequest;

export const zGetFilteredMessagesCountPath = z.object({
    project_id: z.string()
});

/**
 * Response Get Filtered Messages Count
 *
 * Successful Response
 */
export const zGetFilteredMessagesCountResponse = z.int();

export const zGetFilteredMessagesBody = zFilteredMessagesRequest;

export const zGetFilteredMessagesPath = z.object({
    project_id: z.string()
});

export const zGetFilteredMessagesQuery = z.object({
    skip: z.int().optional().default(0),
    limit: z.int().optional().default(20)
});

/**
 * Response Get Filtered Messages
 *
 * Successful Response
 */
export const zGetFilteredMessagesResponse = z.array(zMessagePublic);

export const zGetMessageContextBeforePath = z.object({
    project_id: z.string(),
    interview_id: z.string(),
    message_id: z.string()
});

/**
 * Response Get Message Context Before
 *
 * Successful Response
 */
export const zGetMessageContextBeforeResponse = z.array(zMessagePublic);

export const zGetMessageContextAfterPath = z.object({
    project_id: z.string(),
    interview_id: z.string(),
    message_id: z.string()
});

/**
 * Response Get Message Context After
 *
 * Successful Response
 */
export const zGetMessageContextAfterResponse = z.array(zMessagePublic);

export const zGetProjectMonitoringStatsPath = z.object({
    project_id: z.string()
});

export const zGetProjectMonitoringStatsQuery = z.object({
    interview_types: z.array(zInterviewType).optional(),
    start_date: z.iso.datetime().nullish(),
    end_date: z.iso.datetime().nullish()
});

/**
 * Successful Response
 */
export const zGetProjectMonitoringStatsResponse = zMonitoringStats;

export const zResetSessionPath = z.object({
    project_id: z.string().nullable(),
    lang: z.string().length(2)
});

export const zResetSessionQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetChatPath = z.object({
    project_id: z.string().nullable(),
    lang: z.string().length(2)
});

export const zGetChatQuery = z.object({
    folder_id: z.string().nullish()
});

export const zSendChatBody = zAssistanceChatRequest;

export const zSendChatPath = z.object({
    project_id: z.string().nullable(),
    lang: z.string().length(2)
});

export const zSendChatQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Get Experiments
 *
 * Successful Response
 */
export const zGetExperimentsResponse = z.array(zExperimentPublic);

export const zCreateExperimentBody = zExperimentCreate;

/**
 * Successful Response
 */
export const zCreateExperimentResponse = zExperimentPublic;

export const zDeleteExperimentPath = z.object({
    experiment_id: z.string()
});

export const zGenerateExperimentQrPath = z.object({
    experiment_id: z.string()
});

/**
 * Response Get Folders
 *
 * Successful Response
 */
export const zGetFoldersResponse = z.array(zProjectFolderWithProjects);

export const zCreateFolderBody = zProjectFolderCreate;

/**
 * Successful Response
 */
export const zCreateFolderResponse = zProjectFolderPublic;

export const zDeleteFolderPath = z.object({
    folder_id: z.string().nullable()
});

export const zDeleteFolderQuery = z.object({
    project_id: z.string().nullish()
});

export const zEditFolderBody = zProjectFolderEdit;

export const zEditFolderPath = z.object({
    folder_id: z.string().nullable()
});

export const zEditFolderQuery = z.object({
    project_id: z.string().nullish()
});

export const zRemoveCollaboratorPath = z.object({
    folder_id: z.string().nullable()
});

export const zRemoveCollaboratorQuery = z.object({
    user_id: z.string(),
    project_id: z.string().nullish()
});

export const zGetCollaboratorsPath = z.object({
    folder_id: z.string().nullable()
});

export const zGetCollaboratorsQuery = z.object({
    project_id: z.string().nullish()
});

/**
 * Response Get Collaborators
 *
 * Successful Response
 */
export const zGetCollaboratorsResponse = z.array(zCollaboratorPublic);

export const zUpdateCollaboratorRolePath = z.object({
    folder_id: z.string().nullable()
});

export const zUpdateCollaboratorRoleQuery = z.object({
    user_id: z.string(),
    role: zCollaboratorRole,
    project_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zUpdateCollaboratorRoleResponse = zCollaboratorPublic;

export const zAddCollaboratorBody = zCollaboratorCreate;

export const zAddCollaboratorPath = z.object({
    folder_id: z.string().nullable()
});

export const zAddCollaboratorQuery = z.object({
    project_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zAddCollaboratorResponse = zCollaboratorPublic;

export const zCreateProjectBody = zCreateProjectRequest;

export const zCreateProjectPath = z.object({
    folder_id: z.string().nullable()
});

export const zCreateProjectQuery = z.object({
    project_id: z.string().nullish()
});

export const zDeleteParticipantsBody = zDeleteParticipantsRequest;

export const zDeleteParticipantsPath = z.object({
    project_id: z.string().nullable()
});

export const zDeleteParticipantsQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetParticipantsPath = z.object({
    project_id: z.string().nullable()
});

export const zGetParticipantsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Get Participants
 *
 * Successful Response
 */
export const zGetParticipantsResponse = z.array(zParticipantPublic);

export const zAddParticipantBody = zParticipantCreate;

export const zAddParticipantPath = z.object({
    project_id: z.string().nullable()
});

export const zAddParticipantQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zAddParticipantResponse = zParticipantPublic;

export const zDeleteParticipantPath = z.object({
    project_id: z.string().nullable(),
    participant_id: z.string()
});

export const zDeleteParticipantQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetParticipantPath = z.object({
    project_id: z.string().nullable(),
    participant_id: z.string()
});

export const zGetParticipantQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGetParticipantResponse = zParticipantPublic;

export const zUpdateParticipantBody = zParticipantUpdate;

export const zUpdateParticipantPath = z.object({
    project_id: z.string().nullable(),
    participant_id: z.string()
});

export const zUpdateParticipantQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zUpdateParticipantResponse = zParticipantPublic;

export const zExportParticipantsBody = zExportParticipantsRequest;

export const zExportParticipantsPath = z.object({
    project_id: z.string().nullable()
});

export const zExportParticipantsQuery = z.object({
    folder_id: z.string().nullish()
});

export const zExportEmailBundlePath = z.object({
    project_id: z.string().nullable()
});

export const zExportEmailBundleQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zExportEmailBundleResponse = z.string();

/**
 * Reason
 */
export const zOptOutBody = z.string().nullable();

export const zOptOutPath = z.object({
    opt_out_token: z.string()
});

/**
 * Successful Response
 */
export const zOptOutResponse = zParticipantPublic;

/**
 * Participants
 */
export const zAddParticipantsBody = z.array(zParticipantCreate);

export const zAddParticipantsPath = z.object({
    project_id: z.string().nullable()
});

export const zAddParticipantsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Add Participants
 *
 * Successful Response
 */
export const zAddParticipantsResponse = z.array(zParticipantPublic);

export const zUploadParticipantsBody = zBodyUploadParticipants;

export const zUploadParticipantsPath = z.object({
    project_id: z.string().nullable()
});

export const zUploadParticipantsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Upload Participants
 *
 * Successful Response
 */
export const zUploadParticipantsResponse = z.array(zParticipantPublic);

export const zGetParticipantEmailTemplatePath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2)
});

export const zGetParticipantEmailTemplateQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGetParticipantEmailTemplateResponse = zParticipantEmailTemplateRequest;

export const zSetParticipantEmailTemplateBody = zParticipantEmailTemplateRequest;

export const zSetParticipantEmailTemplatePath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2)
});

export const zSetParticipantEmailTemplateQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zSetParticipantEmailTemplateResponse = zParticipantEmailTemplateRequest;

export const zListParticipantEmailAttachmentsPath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2)
});

export const zListParticipantEmailAttachmentsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response List Participant Email Attachments
 *
 * Successful Response
 */
export const zListParticipantEmailAttachmentsResponse = z.array(zParticipantEmailAttachment);

export const zUploadParticipantEmailAttachmentsBody = zBodyUploadParticipantEmailAttachments;

export const zUploadParticipantEmailAttachmentsPath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2)
});

export const zUploadParticipantEmailAttachmentsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Upload Participant Email Attachments
 *
 * Successful Response
 */
export const zUploadParticipantEmailAttachmentsResponse = z.array(zParticipantEmailAttachment);

export const zDeleteParticipantEmailAttachmentPath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2),
    filename: z.string()
});

export const zDeleteParticipantEmailAttachmentQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Delete Participant Email Attachment
 *
 * Successful Response
 */
export const zDeleteParticipantEmailAttachmentResponse = z.array(zParticipantEmailAttachment);

export const zSendParticipantEmailsBody = zSendParticipantEmailRequest;

export const zSendParticipantEmailsPath = z.object({
    project_id: z.string().nullable()
});

export const zSendParticipantEmailsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zSendParticipantEmailsResponse = zSendParticipantEmailResponse;

export const zGetParticipantReminderEmailTemplatePath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2)
});

export const zGetParticipantReminderEmailTemplateQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGetParticipantReminderEmailTemplateResponse = zParticipantEmailTemplateRequest;

export const zSetParticipantReminderEmailTemplateBody = zParticipantEmailTemplateRequest;

export const zSetParticipantReminderEmailTemplatePath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2)
});

export const zSetParticipantReminderEmailTemplateQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zSetParticipantReminderEmailTemplateResponse = zParticipantEmailTemplateRequest;

export const zListParticipantReminderEmailAttachmentsPath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2)
});

export const zListParticipantReminderEmailAttachmentsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response List Participant Reminder Email Attachments
 *
 * Successful Response
 */
export const zListParticipantReminderEmailAttachmentsResponse = z.array(zParticipantEmailAttachment);

export const zUploadParticipantReminderEmailAttachmentsBody = zBodyUploadParticipantReminderEmailAttachments;

export const zUploadParticipantReminderEmailAttachmentsPath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2)
});

export const zUploadParticipantReminderEmailAttachmentsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Upload Participant Reminder Email Attachments
 *
 * Successful Response
 */
export const zUploadParticipantReminderEmailAttachmentsResponse = z.array(zParticipantEmailAttachment);

export const zDeleteParticipantReminderEmailAttachmentPath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2),
    filename: z.string()
});

export const zDeleteParticipantReminderEmailAttachmentQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Delete Participant Reminder Email Attachment
 *
 * Successful Response
 */
export const zDeleteParticipantReminderEmailAttachmentResponse = z.array(zParticipantEmailAttachment);

export const zSendParticipantReminderEmailsBody = zSendParticipantEmailRequest;

export const zSendParticipantReminderEmailsPath = z.object({
    project_id: z.string().nullable()
});

export const zSendParticipantReminderEmailsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zSendParticipantReminderEmailsResponse = zSendParticipantEmailResponse;

export const zDeleteProjectPath = z.object({
    project_id: z.string().nullable()
});

export const zDeleteProjectQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetProjectPath = z.object({
    project_id: z.string().nullable()
});

export const zGetProjectQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGetProjectResponse = zProjectPublic;

export const zCloneProjectPath = z.object({
    project_id: z.string().nullable()
});

export const zCloneProjectQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zCloneProjectResponse = zProjectPublic;

export const zRemoveProjectLanguageBody = zLanguageCode;

export const zRemoveProjectLanguagePath = z.object({
    project_id: z.string().nullable()
});

export const zRemoveProjectLanguageQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Remove Project Language
 *
 * Successful Response
 */
export const zRemoveProjectLanguageResponse = z.array(zLanguageDict);

export const zGetProjectLanguagesPath = z.object({
    project_id: z.string()
});

/**
 * Response Get Project Languages
 *
 * Successful Response
 */
export const zGetProjectLanguagesResponse = z.array(zLanguageDict);

export const zAddProjectLanguageBody = zBodyAddProjectLanguage;

export const zAddProjectLanguagePath = z.object({
    project_id: z.string().nullable()
});

export const zAddProjectLanguageQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Add Project Language
 *
 * Successful Response
 */
export const zAddProjectLanguageResponse = z.array(zLanguageDict);

export const zChangeProjectStatusBody = zProjectStatusChangeRequest;

export const zChangeProjectStatusPath = z.object({
    project_id: z.string().nullable()
});

export const zChangeProjectStatusQuery = z.object({
    folder_id: z.string().nullish()
});

export const zChangeProjectTitleBody = zProjectTitleUpdateRequest;

export const zChangeProjectTitlePath = z.object({
    project_id: z.string().nullable()
});

export const zChangeProjectTitleQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetGuidePath = z.object({
    project_id: z.string().nullable(),
    lang: z.string().length(2)
});

export const zGetGuideQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGetGuideResponse = zInterviewGuideOutput;

export const zCreateGuideBody = zInterviewGuideInput;

export const zCreateGuidePath = z.object({
    project_id: z.string().nullable(),
    lang: z.string().length(2)
});

export const zCreateGuideQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGenerateGuideBody = zInterviewGuideGenerationRequest;

export const zGenerateGuidePath = z.object({
    project_id: z.string().nullable(),
    lang: z.string().length(2)
});

export const zGenerateGuideQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGenerateGuideResponse = zInterviewGuideOutput;

export const zGenerateGuideSectionBody = zQuestionSectionGenerationRequest;

export const zGenerateGuideSectionPath = z.object({
    project_id: z.string().nullable(),
    lang: z.string().length(2)
});

export const zGenerateGuideSectionQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGenerateGuideSectionResponse = zQuestionSection;

export const zGenerateSectionQuestionBody = zQuestionGenerationRequest;

export const zGenerateSectionQuestionPath = z.object({
    project_id: z.string().nullable(),
    lang: z.string().length(2)
});

export const zGenerateSectionQuestionQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGenerateSectionQuestionResponse = zQuestionOutput;

export const zUploadImageBody = zBodyUploadImage;

export const zUploadImagePath = z.object({
    project_id: z.string().nullable()
});

export const zUploadImageQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetInterviewAgentsPath = z.object({
    project_id: z.string().nullable(),
    lang: z.string().length(2)
});

export const zGetInterviewAgentsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGetInterviewAgentsResponse = zAgentConfigsOutput;

export const zCreateInterviewAgentsBody = zAgentConfigsInput;

export const zCreateInterviewAgentsPath = z.object({
    project_id: z.string().nullable(),
    lang: z.string().length(2)
});

export const zCreateInterviewAgentsQuery = z.object({
    folder_id: z.string().nullish()
});

export const zPreviewProbingPromptsBody = zProbingAgentConfig;

export const zPreviewProbingPromptsPath = z.object({
    project_id: z.string().nullable(),
    lang: z.string().length(2)
});

export const zPreviewProbingPromptsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zPreviewProbingPromptsResponse = zProbingPromptPreview;

export const zGetInterviewConfigPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zGetInterviewConfigResponse = zInterviewConfigWithModels;

export const zCreateInterviewConfigBody = zInterviewConfig;

export const zCreateInterviewConfigPath = z.object({
    project_id: z.string().nullable()
});

export const zCreateInterviewConfigQuery = z.object({
    folder_id: z.string().nullish()
});

export const zUpdateExternalParamsBody = zExternalParamsRequest;

export const zUpdateExternalParamsPath = z.object({
    project_id: z.string().nullable()
});

export const zUpdateExternalParamsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGetPromptDefaultsResponse = zProbingPromptSlots;

export const zGetConsentPath = z.object({
    project_id: z.string(),
    language: z.string().length(2)
});

/**
 * Response Get Consent
 *
 * Successful Response
 */
export const zGetConsentResponse = zConsent.nullable();

export const zCreateConsentBody = zConsent;

export const zCreateConsentPath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2)
});

export const zCreateConsentQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetWelcomePath = z.object({
    project_id: z.string(),
    language: z.string().length(2)
});

/**
 * Response Get Welcome
 *
 * Successful Response
 */
export const zGetWelcomeResponse = zWelcome.nullable();

export const zCreateWelcomeBody = zBodyCreateWelcome;

export const zCreateWelcomePath = z.object({
    project_id: z.string().nullable(),
    language: z.string().length(2)
});

export const zCreateWelcomeQuery = z.object({
    folder_id: z.string().nullish()
});

export const zDeleteInterviewsBody = zDeleteInterviewRequest;

export const zDeleteInterviewsPath = z.object({
    project_id: z.string().nullable()
});

export const zDeleteInterviewsQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetInterviewsPath = z.object({
    project_id: z.string().nullable()
});

export const zGetInterviewsQuery = z.object({
    interview_types: z.array(zInterviewType).nullish(),
    created_at: z.iso.datetime().nullish(),
    completed: z.boolean().nullish(),
    folder_id: z.string().nullish(),
    offset: z.int().lte(100).optional().default(0),
    limit: z.int().lte(100).optional().default(20),
    column: z.string().optional().default('created_at'),
    order: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * Successful Response
 */
export const zGetInterviewsResponse = zPaginatedResponseInterviewSummaryPublic;

export const zGetMessagePath = z.object({
    project_id: z.string().nullable(),
    interview_id: z.string(),
    message_id: z.string()
});

export const zGetMessageQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetInterviewMessagesPath = z.object({
    project_id: z.string().nullable(),
    interview_id: z.string()
});

export const zGetInterviewMessagesQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Get Interview Messages
 *
 * Successful Response
 */
export const zGetInterviewMessagesResponse = z.array(zMessagePublic);

export const zGetInterviewAudioPath = z.object({
    project_id: z.string().nullable(),
    interview_id: z.string(),
    filename: z.string()
});

export const zGetInterviewAudioQuery = z.object({
    folder_id: z.string().nullish()
});

export const zExportMessagesBody = zExportMessagesRequest;

export const zExportMessagesPath = z.object({
    project_id: z.string().nullable()
});

export const zExportMessagesQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGenerateProjectQrPath = z.object({
    project_id: z.string().nullable()
});

export const zGenerateProjectQrQuery = z.object({
    folder_id: z.string().nullish()
});

export const zCheckProjectOwnerPath = z.object({
    project_id: z.string()
});

/**
 * Response Check Project Owner
 *
 * Successful Response
 */
export const zCheckProjectOwnerResponse = z.boolean();

export const zGetBackgroundInfoPath = z.object({
    project_id: z.string().nullable(),
    test_id: z.string()
});

export const zGetBackgroundInfoQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGetBackgroundInfoResponse = zBackgroundInfoOptionsOutput;

export const zUpdateBackgroundInfoBody = zUpdateBackgroundInfoRequest;

export const zUpdateBackgroundInfoPath = z.object({
    project_id: z.string().nullable(),
    test_id: z.string()
});

export const zUpdateBackgroundInfoQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetFixedPersonasPath = z.object({
    project_id: z.string().nullable(),
    test_id: z.string()
});

export const zGetFixedPersonasQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Get Fixed Personas
 *
 * Successful Response
 */
export const zGetFixedPersonasResponse = z.array(z.string()).nullable();

export const zUpdateFixedPersonasBody = zUpdateFixedPersonasRequest;

export const zUpdateFixedPersonasPath = z.object({
    project_id: z.string().nullable(),
    test_id: z.string()
});

export const zUpdateFixedPersonasQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetFixedAnswersPath = z.object({
    project_id: z.string().nullable(),
    test_id: z.string()
});

export const zGetFixedAnswersQuery = z.object({
    folder_id: z.string().nullish()
});

export const zUpdateFixedAnswersBody = zUpdateFixedAnswersRequest;

export const zUpdateFixedAnswersPath = z.object({
    project_id: z.string().nullable(),
    test_id: z.string()
});

export const zUpdateFixedAnswersQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetTestSetupsPath = z.object({
    project_id: z.string().nullable()
});

export const zGetTestSetupsQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Response Get Test Setups
 *
 * Successful Response
 */
export const zGetTestSetupsResponse = z.array(zTestSetupPublic);

export const zCreateTestSetupBody = zTestSetupCreate;

export const zCreateTestSetupPath = z.object({
    project_id: z.string().nullable()
});

export const zCreateTestSetupQuery = z.object({
    folder_id: z.string().nullish()
});

/**
 * Successful Response
 */
export const zCreateTestSetupResponse = zTestSetupPublic;

export const zDeleteTestSetupPath = z.object({
    project_id: z.string().nullable(),
    test_id: z.string()
});

export const zDeleteTestSetupQuery = z.object({
    folder_id: z.string().nullish()
});

export const zGetIntervieweePath = z.object({
    project_id: z.string()
});

export const zGetIntervieweeQuery = z.object({
    interview_id: z.string()
});

export const zGetTestStatusPath = z.object({
    project_id: z.string().nullable(),
    test_id: z.string()
});

export const zGetTestStatusQuery = z.object({
    folder_id: z.string().nullish()
});

export const zRunSyntheticTestBody = zSynthesizeRequest;

export const zRunSyntheticTestPath = z.object({
    project_id: z.string().nullable(),
    test_id: z.string()
});

export const zRunSyntheticTestQuery = z.object({
    folder_id: z.string().nullish()
});

export const zCreateInterviewBody = zCreateInterviewRequest;

export const zCreateInterviewHeaders = z.object({
    'user-agent': z.string().nullish(),
    'X-Real-IP': z.string().nullish()
});

export const zCreateInterviewPath = z.object({
    project_id: z.string(),
    lang: zLanguageCode
});

/**
 * Response Create Interview
 *
 * Successful Response
 */
export const zCreateInterviewResponse = z.string();

export const zPutFeedbackBody = zMessageFeedbackResponse;

/**
 * Successful Response
 */
export const zPutFeedbackResponse = zMessageFeedbackResponse;

export const zUploadInterviewImageBody = zBodyUploadInterviewImage;

/**
 * Successful Response
 */
export const zUploadInterviewImageResponse = zMediaUploadResponse;

export const zUploadAudioBody = zBodyUploadAudio;

/**
 * Successful Response
 */
export const zUploadAudioResponse = zMediaUploadResponse;

export const zSynthesizeSpeechBody = zSpeechRequest;

/**
 * Successful Response
 */
export const zSynthesizeSpeechResponse = z.string();

export const zLoginBody = zLoginData;

export const zVerifyLoginCodeBody = zVerifyLoginCodeRequest;

export const zDeleteMeBody = zDeleteAccountRequest;

/**
 * Successful Response
 */
export const zMeResponse = zUserPublic;

export const zUpdateMeBody = zUserSelfUpdate;

/**
 * Successful Response
 */
export const zUpdateMeResponse = zUserPublic;

export const zUpdateMyEmailBody = zUpdateEmailRequest;

/**
 * Successful Response
 */
export const zUpdateMyEmailResponse = zUserPublic;

export const zUpdateMyPasswordBody = zUpdatePasswordRequest;

export const zRegisterBody = zUserCreateRequest;

export const zVerifyEmailBody = zVerifyEmailRequest;

export const zResendVerificationBody = zResendVerificationRequest;

export const zRequestAccessBody = zAccessRequestCreate;

export const zProcessAccessRequestsBody = zAccessRequestsProcessRequest;

export const zDeleteAccessRequestsBody = zAccessRequestsDeleteRequest;

/**
 * Response Get Invitations
 *
 * Successful Response
 */
export const zGetInvitationsResponse = z.array(zInvitationPublic);

export const zCreateInvitationBody = zInvitationCreate;

export const zUpdateInvitationBody = zInvitationUpdate;

export const zUpdateInvitationPath = z.object({
    invitation_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateInvitationResponse = zInvitationPublic;

export const zDeleteInvitationsBody = zInvitationsDeleteRequest;

export const zProxyToEc2ManagerDeletePath = z.object({
    full_path: z.string()
});

export const zProxyToEc2ManagerGetPath = z.object({
    full_path: z.string()
});

export const zProxyToEc2ManagerPatchPath = z.object({
    full_path: z.string()
});

export const zProxyToEc2ManagerPostPath = z.object({
    full_path: z.string()
});

export const zProxyToEc2ManagerPutPath = z.object({
    full_path: z.string()
});

export const zDeleteUserQuery = z.object({
    user_id: z.string()
});

/**
 * Response Get Users
 *
 * Successful Response
 */
export const zGetUsersResponse = z.array(zUserAdmin);

export const zUpdateAdminNoteBody = zAdminNoteUpdate;

export const zUpdateAdminNotePath = z.object({
    user_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateAdminNoteResponse = zUserAdmin;

export const zUpdateUserBody = zUserAdminUpdate;

export const zUpdateUserPath = z.object({
    user_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateUserResponse = zUserAdmin;

/**
 * Response Get Languages
 *
 * Successful Response
 */
export const zGetLanguagesResponse = z.array(zLanguageDict);

export const zNewsletterUnsubscribeBody = zNewsletterRequest;

export const zNewsletterSubscribeBody = zNewsletterRequest;

/**
 * Response Version
 *
 * Successful Response
 */
export const zVersionResponse = zPlatformManifest.nullable();

export const zPlatformVersionPath = z.object({
    platform_version: z.string()
});
